### ISSUE TITLE
Error using Dendron: Paste Link

### ISSUE THREAD

**Issue by gavioto** [dendronhq/dendron#1647]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Errors when pasting links from chrome. The links is copied between "<" ">" symbols, and an error appears. 
Using 

## To Reproduce

1. -Copy the url from crhome
2. - Pase using "Dendron: Paste Link"

## Expected behavior

Expected behaviour when using "Dendron: Paste Link" without an error

## Desktop (please complete the following information)

- OS: Windows 10 20H2
- Browser: Chrome
- Version: 

## Additional context

Error log

[exthost] [error] TypeError: Cannot read property 'note' of undefined
	at P.getParent (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:3629662)
	at d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:60651
	at d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:12691
	at new Promise (<anonymous>)
	at Object.d [as asPromise] (d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:12663)
	at c.resolveParent (d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:60619)
	at c.resolveUnknownParentChain (d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:60340)
	at d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:58584
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here

**Comment by gavioto** [comment]
There is a similar error when using paste here 

[exthost] [error] TypeError: Cannot read property 'title' of undefined
	at d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:3629019
	at d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1595193
	at Pt (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1578574)
	at d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1595168
	at d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1594160
	at d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1600651
	at Vn (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1594131)
	at Wn (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1595140)
	at Function.<anonymous> (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1613668)
	at wt (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1577809)
	at Function.sortBy (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:1608917)
	at P.sortChildren (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:3629001)
	at P.parseTree (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:3630040)
	at d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:3629505
	at Array.flatMap (<anonymous>)
	at P.getChildren (d:\home\user\portapps\vscodium-portable\data\extensions\dendron.dendron-0.66.1\dist\extension.js:8:3629475)
	at c.fetchChildrenNodes (d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:61415)
	at c.getChildren (d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:58096)
	at d:\home\user\portapps\vscodium-portable\app\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:60840
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by Harshita-mindfire** [comment]
Hello @gavioto, I am unable to repro. Although from the error log you provided, it seems like the engine is not able to recognize the note. Can you try running `Dendron: Reload Index` first and then Paste Link.
