### ISSUE TITLE
Lookup tool cannot find any notes

### ISSUE THREAD

**Issue by Tycholiz** [dendronhq/dendron#1752]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

I am working on my secondary machine. I hold all Dendron files in Onedrive, and symlink the entire directory to my local machine. I then open the workspace in this symlink. 

I properly see all of my notes in the sidebar directory structure, but nothing shows up in Lookup tool.

I am getting the ominous looking error:
> No available vaults for file name. This error should never occur! Please report a bug if you have encountered this.

So, here I am.

## Desktop (please complete the following information)

- OS: MacOS Big Sur 11.6.1
- Browser: Chrome
- Version: 95.0.4638.69

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here
```
{"level":30,"time":1637349109349,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1637349109513,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/Users/kyletycholiz/Library/Application Support/Code/logs/20211119T110715/exthost1/dendron.dendron","extensionPath":"/Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1","extensionUri":"/Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1","workspaceFile":"/Users/kyletycholiz/Dendron/dendron.code-workspace","workspaceFolders":["/Users/kyletycholiz/Dendron/tech","/Users/kyletycholiz/Dendron/personal","/Users/kyletycholiz/Dendron/thoughts-on"]}
{"level":30,"time":1637349109514,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1637349109514,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1637349109515,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1637349109515,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1637349109522,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1637349109557,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.69.1","previousWorkspaceVersion":"0.69.1","previousGlobalVersion":"0.69.1","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1637349109564,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1637349109565,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1637349109565,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1637349109565,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1637349109565,"pid":1800,"hostname":"RIV-712217M","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1637349109565,"pid":1800,"hostname":"RIV-712217M","name":"dendron","msg":"Segment Residual Cache Path is at undefined"}
{"level":30,"time":1637349109737,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1637349109737,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1637349109738,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1637349109738,"pid":1800,"hostname":"RIV-712217M","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1637349109738,"pid":1800,"hostname":"RIV-712217M","name":"dendron","msg":"Segment Residual Cache Path is at /Users/kyletycholiz/Library/Application Support/Code/User/globalStorage/dendron.dendron/segmentresidualcache.log"}
{"level":30,"time":1637349109738,"pid":1800,"hostname":"RIV-712217M","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1637349109750,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"_activate","workspaceInstallStatus":"NO_CHANGE","currentVersion":"0.69.1","previousWorkspaceVersion":"0.69.1","previousGlobalVersion":"0.69.1","platform":"darwin","extensions":[{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"redhat.vscode-yaml"}],"vaults":[]}
{"level":30,"time":1637349109753,"pid":1800,"hostname":"RIV-712217M","name":"execServer","state":"enter"}
{"level":30,"time":1637349109755,"pid":1800,"hostname":"RIV-712217M","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1637349110610,"pid":1818,"hostname":"RIV-712217M","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1637349110610,"pid":1818,"hostname":"RIV-712217M","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1637349110610,"pid":1818,"hostname":"RIV-712217M","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1637349110610,"pid":1818,"hostname":"RIV-712217M","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1637349110795,"pid":1800,"hostname":"RIV-712217M","name":"execServer","state":"message","message":"49750"}
{"level":30,"time":1637349110795,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":1818}
{"level":30,"time":1637349110795,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"_activate","msg":"post-start-server","port":49750,"durationStartServer":1238}
{"level":30,"time":1637349110800,"pid":1800,"hostname":"RIV-712217M","name":"logger","ctx":"FileStorageV2","wsRoot":"/Users/kyletycholiz/Dendron","vaults":[],"level":"info"}
{"level":30,"time":1637349110801,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1637349110801,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1637349110905,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":104}
{"level":30,"time":1637349110906,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1637349110906,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1637349110910,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1637349110911,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1637349110911,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1637349110911,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1637349110912,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1637349110912,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1637349110913,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1637349110915,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1637349110919,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1637349110920,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1637349110921,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":1358}
{"level":30,"time":1637349110921,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.69.1","previousExtensionVersion":"0.69.1"}
{"level":30,"time":1637349113292,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupCommand:gatherInput","msg":"enter"}
{"level":30,"time":1637349113293,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"LookupControllerV3:new","msg":"enter"}
{"level":30,"time":1637349113293,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"prepareQuickPick","msg":"enter"}
{"level":30,"time":1637349113298,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"prepareQuickPick","msg":"exit"}
{"level":30,"time":1637349113301,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"enter"}
{"level":30,"time":1637349113301,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:pre"}
{"level":30,"time":1637349113302,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"","justActivated":true}
{"level":30,"time":1637349113303,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"","profile":1,"cancelled":false}
{"level":30,"time":1637349113304,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:post"}
{"level":30,"time":1637349113304,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"enter"}
{"level":30,"time":1637349113305,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"exit"}
{"level":30,"time":1637349113305,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"exit"}
{"level":30,"time":1637349129313,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/kyletycholiz/Dendron/thoughts-on/ambition.md"]}
{"level":30,"time":1637349129318,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/kyletycholiz/Dendron/thoughts-on/ambition.md"}
{"level":30,"time":1637349129319,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","uri":"/Users/kyletycholiz/Dendron/thoughts-on/ambition.md","msg":"not in workspace"}
{"level":30,"time":1637349131990,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"b","justActivated":false,"prevQuickpickValue":""}
{"level":30,"time":1637349131994,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349131994,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":3}
{"level":30,"time":1637349131994,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"b","profile":3,"cancelled":false}
{"level":30,"time":1637349132184,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"bu","justActivated":false,"prevQuickpickValue":"b"}
{"level":30,"time":1637349132187,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349132187,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":2}
{"level":30,"time":1637349132187,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"bu","profile":3,"cancelled":false}
{"level":30,"time":1637349132194,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"bus","justActivated":false,"prevQuickpickValue":"bu"}
{"level":30,"time":1637349132195,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349132195,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":1}
{"level":30,"time":1637349132195,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"bus","profile":1,"cancelled":false}
{"level":30,"time":1637349132441,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"busin","justActivated":false,"prevQuickpickValue":"bus"}
{"level":30,"time":1637349132443,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349132443,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":1}
{"level":30,"time":1637349132444,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"busin","profile":2,"cancelled":false}
{"level":30,"time":1637349132454,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"busine","justActivated":false,"prevQuickpickValue":"busin"}
{"level":30,"time":1637349132456,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349132456,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":1}
{"level":30,"time":1637349132456,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"busine","profile":1,"cancelled":false}
{"level":30,"time":1637349132634,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"busines","justActivated":false,"prevQuickpickValue":"busine"}
{"level":30,"time":1637349132635,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349132636,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":1}
{"level":30,"time":1637349132636,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"busines","profile":1,"cancelled":false}
{"level":30,"time":1637349132758,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"business","justActivated":false,"prevQuickpickValue":"busines"}
{"level":30,"time":1637349132759,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349132759,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":1}
{"level":30,"time":1637349132760,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"business","profile":1,"cancelled":false}
{"level":30,"time":1637349133958,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupProvider:onDidAccept","quickpick":"business"}
{"level":30,"time":1637349133958,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"business","justActivated":false,"prevQuickpickValue":"business"}
{"level":30,"time":1637349133958,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"business","profile":0,"cancelled":false}
{"level":30,"time":1637349133961,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"dendron.lookupNote:run","msg":"pre-execute"}
{"level":30,"time":1637349133961,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupCommand:execute","msg":"enter"}
{"level":30,"time":1637349133963,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"getVaultForOpenEditor","msg":"no active doc"}
{"level":30,"time":1637349133963,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit"}
{"level":30,"time":1637349133964,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"LookupControllerV3:onHide","msg":"exit"}
{"level":30,"time":1637349133964,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupCommand:execute","msg":"exit"}
{"level":50,"time":1637349133965,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"dendron.lookupNote:run","error":{"stack":"DendronError: No available vaults for file name. This error should never occur! Please report a bug if you have encountered this.\n    at Function.createInvalidStateError (/Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1/dist/extension.js:2:102958)\n    at Se.getVaultForNewNote (/Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1/dist/extension.js:8:3457993)\n    at Se.acceptNewItem (/Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1/dist/extension.js:8:3456670)\n    at Se.acceptItem (/Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1/dist/extension.js:8:3456242)\n    at /Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1/dist/extension.js:8:3455722\n    at Array.map (<anonymous>)\n    at Se.execute (/Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1/dist/extension.js:8:3455709)\n    at Se.run (/Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1/dist/extension.js:8:3327891)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at /Users/kyletycholiz/.vscode/extensions/dendron.dendron-0.69.1/dist/extension.js:8:3575713\n    at o._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111743)","message":"No available vaults for file name. This error should never occur! Please report a bug if you have encountered this.","name":"DendronError","status":"invalid_state","payload":"{}"}}
{"level":30,"time":1637349403033,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1637349403034,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1637349405358,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupCommand:gatherInput","msg":"enter"}
{"level":30,"time":1637349405361,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"LookupControllerV3:new","msg":"enter"}
{"level":30,"time":1637349405361,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"prepareQuickPick","msg":"enter"}
{"level":30,"time":1637349405368,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"prepareQuickPick","msg":"exit"}
{"level":30,"time":1637349405368,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"enter"}
{"level":30,"time":1637349405368,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:pre"}
{"level":30,"time":1637349405369,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"","justActivated":true}
{"level":30,"time":1637349405372,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"","profile":3,"cancelled":false}
{"level":30,"time":1637349405372,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:post"}
{"level":30,"time":1637349405372,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"enter"}
{"level":30,"time":1637349405373,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"NoteLookupProvider.provide","msg":"exit"}
{"level":30,"time":1637349405373,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"exit"}
{"level":30,"time":1637349406406,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"s","justActivated":false,"prevQuickpickValue":""}
{"level":30,"time":1637349406408,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349406408,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":1}
{"level":30,"time":1637349406408,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"s","profile":1,"cancelled":false}
{"level":30,"time":1637349406685,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"sd","justActivated":false,"prevQuickpickValue":"s"}
{"level":30,"time":1637349406689,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349406689,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":3}
{"level":30,"time":1637349406689,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"sd","profile":3,"cancelled":false}
{"level":30,"time":1637349407065,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"s","justActivated":false,"prevQuickpickValue":"sd"}
{"level":30,"time":1637349407067,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1637349407067,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":1}
{"level":30,"time":1637349407067,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"s","profile":1,"cancelled":false}
{"level":30,"time":1637349407211,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"","justActivated":false,"prevQuickpickValue":"s"}
{"level":30,"time":1637349407212,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"","profile":1,"cancelled":false}
{"level":30,"time":1637349518735,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"SchemaLookupCommand:gatherInput","msg":"enter"}
{"level":30,"time":1637349518737,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"LookupControllerV3:new","msg":"enter"}
{"level":30,"time":1637349518738,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"prepareQuickPick","msg":"enter"}
{"level":30,"time":1637349518738,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"prepareQuickPick","msg":"exit"}
{"level":30,"time":1637349518739,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"enter"}
{"level":30,"time":1637349518739,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:pre"}
{"level":30,"time":1637349518739,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":""}
{"level":30,"time":1637349518739,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"","profile":0,"cancelled":false}
{"level":30,"time":1637349518739,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"onUpdatePickerItems:post"}
{"level":30,"time":1637349518740,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"showQuickPick","msg":"exit"}
{"level":30,"time":1637349518781,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"LookupControllerV3:onHide","msg":"exit"}
{"level":30,"time":1637349519911,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"SchemaLookupCommand","msg":"changeState.hide event received."}
{"level":30,"time":1637349528298,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1637349528298,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1637349528321,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1637349528391,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/kyletycholiz/Library/Application Support/Code/logs/20211119T110715/exthost1/dendron.dendron/dendron.log"]}
{"level":30,"time":1637349528393,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"/Users/kyletycholiz/Library/Application Support/Code/logs/20211119T110715/exthost1/dendron.dendron/dendron.log"}
{"level":30,"time":1637349528394,"pid":1800,"hostname":"RIV-712217M","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","uri":"/Users/kyletycholiz/Library/Application Support/Code/logs/20211119T110715/exthost1/dendron.dendron/dendron.log","msg":"not in workspace"}
```

**Comment by hikchoi** [comment]
Thank you for the issue. I can't reproduce this at the moment since I don't have the exact setup you have, but we'll take a look and see what can be done. Can you confirm that this doesn't happen in your primary machine where you have the files locally?

**Comment by Tycholiz** [comment]
Sorry for late response!

To be clear, I store the Dendron vaults in the cloud (normally Dropbox, but my employer's IT department has banned it, so I'm trying to use Onedrive instead). I then make a local symlink to this Dendron repo. This symlink seems to be irrelevant to the issue though, because I can open the `dendron.code-workspace` file directly from Dropbox, and Lookup works perfectly.

However when it comes to opening the `dendron.code-workspace` file stored in Onedrive, I can't get Lookup to work, no matter if I'm on my primary machine or secondary.

What would be preventing Dendron from being able to find these vaults?

**Comment by evonaut** [comment]
I can reproduce this error with my vault stored in Amazon WorkDocs Drive (v1.0.6370.0 running on Intel macOS 12.3.1) as well.
