### ISSUE TITLE
Migrations read dendron.code-workspace as JSON, not JSONC

### ISSUE THREAD

**Issue by LukeCarrier** [dendronhq/dendron#1790]
## Please select the area your bug applies to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods
- [ ] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [x] Misc (Choose this if your not sure)

## Describe the bug

When running Dendron migrations, they appear to parse `dendron.code-workspace` as a JSON file. VS Code treats it as JSONC, allowing comments and trailing commas in lists. This causes errors like the following:

```console
❯ dendron dev run_migration --migrationVersion 0.70.0
undefined:5
    },
    ^

SyntaxError: /Users/lukecarrier/Code/lukecarrier/brain/dendron.code-workspace: Unexpected token } in JSON at position 46
    at JSON.parse (<anonymous>)
    at Object.readFileSync (/Users/lukecarrier/Code/lukecarrier/brain/node_modules/jsonfile/index.js:52:17)
    at DevCLICommand.runMigration (/Users/lukecarrier/Code/lukecarrier/brain/node_modules/@dendronhq/dendron-cli/lib/src/commands/devCLICommand.js:386:45)
    at DevCLICommand.execute (/Users/lukecarrier/Code/lukecarrier/brain/node_modules/@dendronhq/dendron-cli/lib/src/commands/devCLICommand.js:217:26)
    at Object.CLICommand.eval [as handler] (/Users/lukecarrier/Code/lukecarrier/brain/node_modules/@dendronhq/dendron-cli/lib/src/commands/base.js:49:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It looks like a similar issue may have been addressed in #304.

## To Reproduce

1. Add a trailing comma to a list in your `dendron.code-workspace`
2. Run `dendron dev run_migration --migrationVersion 0.70.0`

## Expected behavior

The command should complete despite the file being valid JSONC and not valid JSON.

## Screenshots

N/A

## Desktop (please complete the following information)

- OS: N/A
- Browser: N/A
- Version: N/A

## Additional context

Workspace configurations can end up containing regular expressions and glob patterns that warrant documentation, and without comments this gets tricky. I think Dendron ought to be able to migrate any workspace configuration VS Code can parse.

## Dendron Log file

N/A

**Comment by jonathanyeung** [comment]
Thanks for filing the issue @LukeCarrier - which version of dendron cli are you using? 

`dendron --version`

@hikchoi  for awareness

**Comment by LukeCarrier** [comment]
Sorry for the delay @jonathanyeung:

```console
❯ dendron --version
0.70.0
```

**Comment by hikchoi** [comment]
This has been resolved with v72. Please let us know if you have any outstanding problems regard this issue. Otherwise this issue will be automatically closed in 4 days
