### ISSUE TITLE
Cannot export with `MarkdownExportV2`

### ISSUE THREAD

**Issue by aleksey-rowan** [dendronhq/dendron#1994]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [x] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I'm getting the "This error should never occur! Please report a bug if you have encountered this." error when trying to export a `MarkdownExportV2` pod.

## To Reproduce

I use the following pod config:

```yml
podId: ec-bs-2
exportScope: Vault
podType: MarkdownExportV2
wikiLinkToURL: false
destination: c:\Users\AR\Desktop\blah
```

Running `Dendron: Export Pod V2` gives the error below.

## Desktop (please complete the following information)

- Version: 0.74
- OS: Windows 10

## Dendron Log file

`
info: {"ctx":"dendron.exportPodv2:run","msg":"pre-execute"}
info: {"ctx":"dendron.exportPodv2:run","msg":"post-execute"}
error: {"ctx":"dendron.markdownexportv2:run","error":{"stack":"DendronError: This error should never occur! Please report a bug if you have encountered this.\n    at t.assertUnreachable (c:\\Users\\AR\\.vscode\\extensions\\dendron.dendron-0.74.0\\dist\\extension.js:2:106648)\n    at Dr.enrichInputs (c:\\Users\\AR\\.vscode\\extensions\\dendron.dendron-0.74.0\\dist\\extension.js:8:3211555)\n    at Dr.run (c:\\Users\\AR\\.vscode\\extensions\\dendron.dendron-0.74.0\\dist\\extension.js:8:3052356)\n    at runMicrotasks (<anonymous>:null:null)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n","message":"This error should never occur! Please report a bug if you have encountered this.","name":"DendronError","status":"unknown","payload":"{}"}}
`

**Comment by aleksey-rowan** [comment]
Oh, there is already an existing issue: https://github.com/dendronhq/dendron/issues/1838.
