### ISSUE TITLE
Scratch note sometimes auto-creates with bad frontmatter

### ISSUE THREAD

**Issue by raeyulca** [dendronhq/dendron#2329]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Scratch notes created with the 'Create Scratch note` command  sometimes have the title created without quotes. This leads to the build error `value.replace() is not a function` when running `npx dendron publish build`.

## To Reproduce

1. Have scratch note config set to the following:
```
    scratch:
        name: ''
        dateFormat: y.MM.dd.HHmmss
        addBehavior: childOfCurrent
```
2. Use the command `ctrl + shift + s` to create a new scratch note
3. Press `Enter` to create the note.

## Expected behavior

I expected the note to have a title encased in quotes.

## Desktop (please complete the following information)

- OS: Windows
- Browser: n/a
- Version: 0.80.2

## Additional context

I have noticed that this error occurs most frequently when the title of the note has a leading zero. I haven't been able to reproduce it 100% of the time.

## Dendron Log file

Please attach the output of `> Dev:Dendron: Open Logs` here
[scratch-log-output.txt](https://github.com/dendronhq/dendron/files/7985349/scratch-log-output.txt)

**Comment by Harshita-mindfire** [comment]
Thanks for reporting the issue!
I was unable to repro this. Does this happen more frequently?

**Comment by raeyulca** [comment]
I was just able to repro. It happens most frequently between 12AM and 09:59AM

**Comment by vialcollet** [comment]
Hi
None of my frantmatters is created with quotes.
I also have this error when publishing: `TypeError: value.replace is not a function`.
I noticed that dendron doctor fixFrontmatter removes quotes where I have added them.

What is finally expected? Quoted titles or unquoted titles?

Here is the error I get when publishing:

```bash
 generating metadata for publishing...
⠼ error {"stack":"TypeError: value.replace is not a function\n    at encode (/home/bastien/notes/cwt/node_modules/stringify-entities/lib/core.js:7:17)\n    at encode (/home/bastien/notes/cwt/node_modules/stringify-entities/lib/encode.js:12:10)\n    at Object.serializeText [as text] (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/text.js:12:7)\n    at serialize (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/one.js:25:29)\n    at all (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/all.js:14:22)\n    at Object.serializeElement [as element] (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/element.js:33:13)\n    at serialize (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/one.js:25:29)\n    at all (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/all.js:14:22)\n    at Object.serializeElement [as element] (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/element.js:33:13)\n    at serialize (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/one.js:25:29)","message":"value.replace is not a function"}
{"level":50,"time":1644834671418,"pid":1875,"hostname":"PC-Curuba","name":"publish <cmd>","stack":"TypeError: value.replace is not a function\n    at encode (/home/bastien/notes/cwt/node_modules/stringify-entities/lib/core.js:7:17)\n    at encode (/home/bastien/notes/cwt/node_modules/stringify-entities/lib/encode.js:12:10)\n    at Object.serializeText [as text] (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/text.js:12:7)\n    at serialize (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/one.js:25:29)\n    at all (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/all.js:14:22)\n    at Object.serializeElement [as element] (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/element.js:33:13)\n    at serialize (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/one.js:25:29)\n    at all (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/all.js:14:22)\n    at Object.serializeElement [as element] (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/element.js:33:13)\n    at serialize (/home/bastien/notes/cwt/node_modules/hast-util-to-html/lib/one.js:25:29)","type":"Error","msg":"value.replace is not a function"}
```

**Comment by vialcollet** [comment]
I can confirm that missing title quotes is the issue.
I wrote the following script and after executing it, everything exports properly.
```bash
for f in vault/*.md
do sed -i -E "s/^title: ([^']*)$/title: '\1'/g" "$f"
done
```

**Comment by ScriptAutomate** [comment]
To expand on this, this seems to be a larger and confusing bug:

- It isn't just a scratch note issue but a Dendron issue with handling notes with names starting with `0` (zero).
- Scratch notes that include `0` in the title will note be quoted properly
- If you create any note, such as `my.note.01234`, it WILL include quotes
- You can add quotes after the fact to a scratch note, but things can get strange if you try to run `Dendron: Doctor` -> `fixFrontmatter`, as it doesn't know how to handle notes starting with a zero. It seems to _rename_ the `title` attribute of the note, and remove quotes!
- If you purposely break a working note, such as `my.note.01234` by renaming the `title: '01234'`, to be `title: 01234`, you will run into the same weird behavior from `Dendron: Doctor` -> `fixFrontmatter` where it doesn't know what to do, and it will rename the `title` to a completely different value

To replicate the scratch behavior, simply make the note:
```
scratch.2022.02.25.0078
```
The `title` attribute will not add quotes, and `Dendron: Doctor` -> `fixFrontmatter` will get confused by it.

Can also replicate by making `my.note.01234`, removing quotes, and attempting to run `Dendron: Doctor` -> `fixFrontmatter`

**Comment by ScriptAutomate** [comment]
Another potentially related bug, where Dendron doesn't know what to do with notes starting with `0` inside of title when using commands like `Copy Note Link`.

Example:
- Note with title `09` (ex. `my.journal.2022.03.09`)
- Try using `Copy Note Link`
- Pasting the link will show that the Title wasn't properly copied, resulting in `[[0|my.journal.2022.03.09]]` instead of `[[09|my.journal.2022.03.09]]`

The trend seems to be that `0` at the start of a title causes weird behavior across multiple commands in Dendron

**Comment by SeriousBug** [comment]
Hi, we added a fix towards this problem with Dendron 0.86. Dendron now always makes sure that the title is internally a string (not a number) to avoid this issue.

If you were experiencing this problem before, could you let us know if you keep experiencing it after updating?

**Comment by raeyulca** [comment]
The problem has been slightly fixed.
When creating a note with the name `foo.01.02`, where `foo.01` does not currently exist, the note `foo.01` has a title value without quotes, while `foo.01.02` has a title value with quotes.

**Comment by SeriousBug** [comment]
@raeyulca I see, does it still cause errors?

**Comment by raeyulca** [comment]
Yes, it still produces the `value.replace is not a function` error.
