### ISSUE TITLE
ENOENT dendron.code-workspace errors in the log for native workspaces

### ISSUE THREAD

**Issue by SeriousBug** [dendronhq/dendron#2409]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [x] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

The error log is full of errors like this:
```
{"level":50,"time":1644798723387,"pid":1517455,"hostname":"eclipse","name":"logger","errno":-2,"syscall":"open","code":"ENOENT","path":"/home/kaan/Projects/project/docs/dendron.code-workspace","stack":"Error: ENOENT: no such file or directory, open '/home/kaan/Projects/project/docs/dendron.code-workspace'\n    at Object.openSync (fs.js:476:3)\n    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)\n    at Object.readFileSync (fs.js:377:35)\n    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)\n    at t.readJSONWithCommentsSync (/home/kaan/.vscode/extensions/dendron.nightly-0.81.4/dist/server.js:2:164242)\n    at b.getWorkspaceConfig (/home/kaan/.vscode/extensions/dendron.nightly-0.81.4/dist/server.js:2:386403)\n    at Function.getFM (/home/kaan/.vscode/extensions/dendron.nightly-0.81.4/dist/server.js:2:331305)\n    at Function._procRemark (/home/kaan/.vscode/extensions/dendron.nightly-0.81.4/dist/server.js:2:332707)\n    at Function.procRemarkParse (/home/kaan/.vscode/extensions/dendron.nightly-0.81.4/dist/server.js:2:335190)\n    at t.runAllDecorators (/home/kaan/.vscode/extensions/dendron.nightly-0.81.4/dist/server.js:2:249979)","type":"Error","msg":"ENOENT: no such file or directory, open '/home/kaan/Projects/project/docs/dendron.code-workspace'"}
```

## To Reproduce

1. Create a native workspace
2. Open any note and start typing

## Desktop (please complete the following information)

- OS: Linux
- Version: 0.81.4

## Additional context

May be related to #2405

**Comment by jonathanyeung** [comment]
Created [[Enoent Dendroncode Workspace Errors in the Log for Native Workspaces|dendron://private/task.2022.02.14.enoent-dendroncode-workspace-errors-in-the-log-for-native-workspaces]]

> May be related to https://github.com/dendronhq/dendron/pull/2405

Let's test it again after we merge it, if it does resolve it, let's dupe the task then.
