### ISSUE TITLE
`npx dendron publish init` not finishing 

### ISSUE THREAD

**Issue by oolonek** [dendronhq/dendron#2659]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When publishing a fresh new dendron workspace.
After the following sequence of commands :

`npm install @dendronhq/dendron-cli@latest`
`echo .next >> .gitignore`
`npx dendron publish init`

I get the following error 

```
npx dendron publish init                                                                  

🌱 checking if .next directory exists.
🌱 .next directory does not exist
🌱 Initializing NextJS template.
🌱 Successfully cloned.
⠴ Installing dependencies... This may take a while.{"level":50,"time":1648663378523,"pid":92602,"hostname":"vpn-client-44-194.unifr.ch","name":"publish <cmd>","shortMessage":"Command failed with exit code 1: npm install","command":"npm install","exitCode":1,"stdout":"","stderr":"npm ERR! code ERESOLVE\nnpm ERR! ERESOLVE unable to resolve dependency tree\nnpm ERR! \nnpm ERR! While resolving: @dendronhq/nextjs-template@0.85.0\nnpm ERR! Found: three@0.139.0\nnpm ERR! node_modules/three\nnpm ERR!   peer three@\">=0.139\" from @react-three/fiber@8.0.1\nnpm ERR!   node_modules/@react-three/fiber\nnpm ERR!     peerOptional @react-three/fiber@\"*\" from framer-motion@5.6.0\nnpm ERR!     node_modules/framer-motion\nnpm ERR!       peer framer-motion@\"3.x || 4.x || 5.x\" from @chakra-ui/react@1.7.4\nnpm ERR!       node_modules/@chakra-ui/react\nnpm ERR!         @chakra-ui/react@\"^1.6.7\" from the root project\nnpm ERR! \nnpm ERR! Could not resolve dependency:\nnpm ERR! peerOptional three@\"^0.135.0\" from framer-motion@5.6.0\nnpm ERR! node_modules/framer-motion\nnpm ERR!   peer framer-motion@\"3.x || 4.x || 5.x\" from @chakra-ui/react@1.7.4\nnpm ERR!   node_modules/@chakra-ui/react\nnpm ERR!     @chakra-ui/react@\"^1.6.7\" from the root project\nnpm ERR! \nnpm ERR! Fix the upstream dependency conflict, or retry\nnpm ERR! this command with --force, or --legacy-peer-deps\nnpm ERR! to accept an incorrect (and potentially broken) dependency resolution.\nnpm ERR! \nnpm ERR! See /Users/pma/.npm/eresolve-report.txt for a full report.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/pma/.npm/_logs/2022-03-30T18_02_48_323Z-debug-0.log","failed":true,"timedOut":false,"isCanceled":false,"killed":false,"stack":"Error: Command failed with exit code 1: npm install\nnpm ERR! code ERESOLVE\nnpm ERR! ERESOLVE unable to resolve dependency tree\nnpm ERR! \nnpm ERR! While resolving: @dendronhq/nextjs-template@0.85.0\nnpm ERR! Found: three@0.139.0\nnpm ERR! node_modules/three\nnpm ERR!   peer three@\">=0.139\" from @react-three/fiber@8.0.1\nnpm ERR!   node_modules/@react-three/fiber\nnpm ERR!     peerOptional @react-three/fiber@\"*\" from framer-motion@5.6.0\nnpm ERR!     node_modules/framer-motion\nnpm ERR!       peer framer-motion@\"3.x || 4.x || 5.x\" from @chakra-ui/react@1.7.4\nnpm ERR!       node_modules/@chakra-ui/react\nnpm ERR!         @chakra-ui/react@\"^1.6.7\" from the root project\nnpm ERR! \nnpm ERR! Could not resolve dependency:\nnpm ERR! peerOptional three@\"^0.135.0\" from framer-motion@5.6.0\nnpm ERR! node_modules/framer-motion\nnpm ERR!   peer framer-motion@\"3.x || 4.x || 5.x\" from @chakra-ui/react@1.7.4\nnpm ERR!   node_modules/@chakra-ui/react\nnpm ERR!     @chakra-ui/react@\"^1.6.7\" from the root project\nnpm ERR! \nnpm ERR! Fix the upstream dependency conflict, or retry\nnpm ERR! this command with --force, or --legacy-peer-deps\nnpm ERR! to accept an incorrect (and potentially broken) dependency resolution.\nnpm ERR! \nnpm ERR! See /Users/pma/.npm/eresolve-report.txt for a full report.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/pma/.npm/_logs/2022-03-30T18_02_48_323Z-debug-0.log\n    at makeError (/Users/pma/Dropbox/DWS/activity-report/node_modules/@dendronhq/engine-server/node_modules/execa/lib/error.js:59:11)\n    at handlePromise (/Users/pma/Dropbox/DWS/activity-report/node_modules/@dendronhq/engine-server/node_modules/execa/index.js:114:26)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.installDependencies (/Users/pma/Dropbox/DWS/activity-report/node_modules/@dendronhq/pods-core/lib/builtin/NextjsExportPod.js:68:9)\n    at async PublishCLICommand._installDependencies (/Users/pma/Dropbox/DWS/activity-report/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:364:9)\n    at async PublishCLICommand._initialize (/Users/pma/Dropbox/DWS/activity-report/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:348:9)\n    at async PublishCLICommand.init (/Users/pma/Dropbox/DWS/activity-report/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:279:13)\n    at async PublishCLICommand.execute (/Users/pma/Dropbox/DWS/activity-report/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:116:33)\n    at async Object.CLICommand.eval [as handler] (/Users/pma/Dropbox/DWS/activity-report/node_modules/@dendronhq/dendron-cli/lib/src/commands/base.js:58:25)","type":"Error","msg":"Command failed with exit code 1: npm install\nnpm ERR! code ERESOLVE\nnpm ERR! ERESOLVE unable to resolve dependency tree\nnpm ERR! \nnpm ERR! While resolving: @dendronhq/nextjs-template@0.85.0\nnpm ERR! Found: three@0.139.0\nnpm ERR! node_modules/three\nnpm ERR!   peer three@\">=0.139\" from @react-three/fiber@8.0.1\nnpm ERR!   node_modules/@react-three/fiber\nnpm ERR!     peerOptional @react-three/fiber@\"*\" from framer-motion@5.6.0\nnpm ERR!     node_modules/framer-motion\nnpm ERR!       peer framer-motion@\"3.x || 4.x || 5.x\" from @chakra-ui/react@1.7.4\nnpm ERR!       node_modules/@chakra-ui/react\nnpm ERR!         @chakra-ui/react@\"^1.6.7\" from the root project\nnpm ERR! \nnpm ERR! Could not resolve dependency:\nnpm ERR! peerOptional three@\"^0.135.0\" from framer-motion@5.6.0\nnpm ERR! node_modules/framer-motion\nnpm ERR!   peer framer-motion@\"3.x || 4.x || 5.x\" from @chakra-ui/react@1.7.4\nnpm ERR!   node_modules/@chakra-ui/react\nnpm ERR!     @chakra-ui/react@\"^1.6.7\" from the root project\nnpm ERR! \nnpm ERR! Fix the upstream dependency conflict, or retry\nnpm ERR! this command with --force, or --legacy-peer-deps\nnpm ERR! to accept an incorrect (and potentially broken) dependency resolution.\nnpm ERR! \nnpm ERR! See /Users/pma/.npm/eresolve-report.txt for a full report.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/pma/.npm/_logs/2022-03-30T18_02_48_323Z-debug-0.log"}
```
Here is the error log 

[2022-03-30T18_02_48_323Z-debug-0.log](https://github.com/dendronhq/dendron/files/8383309/2022-03-30T18_02_48_323Z-debug-0.log)

## To Reproduce

1. Initialize new Dendron workspace
2. `npm install @dendronhq/dendron-cli@latest`
3. `echo .next >> .gitignore`
4. `npx dendron publish init`

## Expected behavior

No error message.

## Desktop (please complete the following information)

- OS: macOS 10.13
- Versions (all that apply to bug):
  - Dendron : 0.84.0
  - npx : 8.5.5
  - node : v17.8.0

**Comment by rlh1994** [comment]
Also seeing this on a gitlab pages build

**Comment by kevinslin** [comment]
can repro the error and currently working on fix

**Comment by kevinslin** [comment]
heads up - this issue should now be fixed. if you re-run the workflow, your actions should pick up the latest version of nextjs-template with the fix

**Comment by aleksey-rowan** [comment]
`npx dendron publish init` now runs without errors, but `dendron publish dev` fails and exists on windows (see below):

```sh
$ dendron publish dev
🌱 checking if NextJS template is initialized
🌱 NextJS template is already initialized.
generating metadata for publishing...
WARN: --query and --vault parameter not implemented for podType export

> @dendronhq/nextjs-template@0.88.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Attempted to load @next/swc-win32-x64-gnu, but it was not installed
info  - Attempted to load @next/swc-win32-x64-msvc, but it was not installed
```

**Comment by Harshita-mindfire** [comment]
Hello @aleksey-rowan @oolonek, checking if this is still an issue?
`dendron publish dev` should now use the updated `@dendronhq/nextjs-template@0.95.0`
