### ISSUE TITLE
[Bug] Import Markdown pod Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MrGlitchByte** [dendronhq/dendron#2710]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [x] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Attempted to use the `Import Markdown` pod to migrate Obsidian files.
```yaml
# description: Where to import from
# type: string
# required: true
src: /Users/glitch/Documents/vault/

# description: name of vault to import into
# type: string
# required: true
vaultName: vault
```
All other params were left to default.

## To Reproduce

1. Open command palette.
2. Select "Dendron: Import Pod:
3. Select "dendron.markdown"
4. Configure config.yaml defaults
5. Run `Import Markdown` pod
6.  See error

## Expected behavior

All folders and files to be moved from Obsidian to Dendron format.

## Desktop (please complete the following information)

- OS: macOS Monterey M1
- Browser (if with published websites; include version): firefox
- Versions (all that apply to bug):
  - Dendron Extension: 0.89.0
  - VS Code version: 1.66
  - Dendron CLI: n/a

## Dendron Log file
```json
{"level":30,"time":1649298611229,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":953}
{"level":50,"time":1649298611229,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"ReloadIndex.execute","error":{"stack":"DendronError: Multiple errors: \n - Failed to read links in note __index\n - Failed to read links in note 96_research.oscp\n    at h.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:296470)\n    at async c.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:18712)\n    at async /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:25945","message":"Multiple errors: \n - Failed to read links in note __index\n - Failed to read links in note 96_research.oscp","name":"DendronError","status":"unknown","payload":"[{\"stack\":\"DendronError: Failed to read links in note __index\\n    at /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:276665\\n    at Array.map (<anonymous>)\\n    at m._initNotes (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:275775)\\n    at async /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:273437\\n    at async Promise.all (index 0)\\n    at async m.initNotes (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:273345)\\n    at async m.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:269100)\\n    at async h.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:295899)\\n    at async c.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:18712)\\n    at async /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:25945\",\"message\":\"Failed to read links in note __index\",\"name\":\"DendronError\",\"status\":\"unknown\",\"payload\":\"{\\\"msg\\\":\\\"e is not iterable\\\",\\\"stack\\\":\\\"TypeError: e is not iterable\\\\n    at /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:359174\\\\n    at Function.findLinks (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:360497)\\\\n    at /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:276536\\\\n    at Array.map (<anonymous>)\\\\n    at m._initNotes (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:275775)\\\\n    at async /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:273437\\\\n    at async Promise.all (index 0)\\\\n    at async m.initNotes (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:273345)\\\\n    at async m.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:269100)\\\\n    at async h.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:295899)\\\"}\"},{\"stack\":\"DendronError: Failed to read links in note 96_research.oscp\\n    at /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:276665\\n    at Array.map (<anonymous>)\\n    at m._initNotes (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:275775)\\n    at async /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:273437\\n    at async Promise.all (index 0)\\n    at async m.initNotes (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:273345)\\n    at async m.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:269100)\\n    at async h.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:295899)\\n    at async c.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:18712)\\n    at async /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:25945\",\"message\":\"Failed to read links in note 96_research.oscp\",\"name\":\"DendronError\",\"status\":\"unknown\",\"payload\":\"{\\\"msg\\\":\\\"e is not iterable\\\",\\\"stack\\\":\\\"TypeError: e is not iterable\\\\n    at /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:359174\\\\n    at Function.findLinks (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:360497)\\\\n    at /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:276536\\\\n    at Array.map (<anonymous>)\\\\n    at m._initNotes (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:275775)\\\\n    at async /Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:273437\\\\n    at async Promise.all (index 0)\\\\n    at async m.initNotes (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:273345)\\\\n    at async m.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:269100)\\\\n    at async h.init (/Users/glitch/.vscode/extensions/dendron.dendron-0.89.0/dist/server.js:2:295899)\\\"}\"}]"},"msg":"unable to initialize engine"}
{"level":30,"time":1649298611232,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1649298611232,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"dendron.impoglitchPod:run","msg":"post-execute"}
{"level":30,"time":1649298621607,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["extension-output-lextudio.restructuredtext-#2"]}
{"level":30,"time":1649298621607,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1649298621607,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1649298621608,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["extension-output-lextudio.restructuredtext-#2","/Users/glitch/Documents/mindspace/pods/dendron.markdown/config.impoglitch.yml"]}
{"level":30,"time":1649298621609,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1649298626262,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/glitch/Documents/mindspace/pods/dendron.markdown/config.impoglitch.yml","reason":"Manual","msg":"enter"}
{"level":30,"time":1649298631887,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"dendron.impoglitchPod:run","msg":"pre-execute"}
{"level":30,"time":1649298631887,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":{"ctx":"ImpoglitchPod"},"msg":"enter","podChoice":"dendron.markdown"}
{"level":50,"time":1649298648473,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"dendron.impoglitchPod:run","error":{"name":"DendronError","status":"unknown","payload":"{}","innerError":{}}}
{"level":30,"time":1649299014768,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1649299014769,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1649299014781,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
{"level":30,"time":1649299014835,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["extension-output-lextudio.restructuredtext-#2"]}
{"level":30,"time":1649299014835,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1649299014835,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","editor":"undefined"}
{"level":30,"time":1649299014837,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["extension-output-lextudio.restructuredtext-#2","/Users/glitch/Library/Application Suppoglitch/Code/logs/20220405T143356/exthost10/dendron.dendron/dendron.log"]}
{"level":30,"time":1649299014838,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1649299014839,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"dendron.log"}
```

**Comment by MrGlitchByte** [comment]
So I got rid of the troublesome files, but still receive the same error when choosing a different subdir to import.
```yaml
{"level":50,"time":1649300312671,"pid":88520,"hostname":"glitch.local","name":"dendron","ctx":"dendron.importPod:run","error":{"name":"DendronError","status":"unknown","payload":"{}","innerError":{}}}
```

**Comment by jonathanyeung** [comment]
Additional info - seems to be tripping up when notes are large.  With this kind of error msg, I'm guessing it's an issue with the markdown parsing logic not being able to handle such a large file.  Maybe the first mitigation we can do is to handle that error gracefully and point out to the user which files are causing issues.
