### ISSUE TITLE
`Dendron: Site Build` command not found as per the docs and the yaml schema of `site:` is also not present

### ISSUE THREAD

**Issue by shivammehta007** [dendronhq/dendron#3045]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [X] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

In the tutorial to publish to github pages: https://wiki.dendron.so/notes/230d0ccf-5758-4a8f-b39b-3b68e1482e2b/ It says that there should be a command: `Dendron: Site Build` and there should be a schema item called: 
```yaml
site:
    assetsPrefix: dendron-publish-sample
    siteUrl: https://kevinslin.github.io
```
But both are missing and my yaml is giving error: 
```
Namespace for configurations that affect the workspace

Source: dendron-yml.validator.json

Missing property "enableHandlebarTemplates".yaml-schema: file:///Users/shivam/.vscode/extensions/dendron.dendron-0.97.0/dist/dendron-yml.validator.json
Missing property "enableFullHierarchyNoteTitle".yaml-schema: file:///Users/shivam/.vscode/extensions/dendron.dendron-0.97.0/dist/dendron-yml.validator.json
```

## To Reproduce

1. Go to Cmd+shift+p
2. Click on Dendron: Configure (yaml)
3. Scroll down to workspace

Also cannot find Dendron: Site build command
1. Cmd+ shift +p
2. Dendron: Dendron: Site Build
3.  Command not found

## Expected behavior

Should be able to build the docs.

## Screenshots

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/9089131/172047910-f4528626-a2dd-4796-ba7c-44a449ea0fb4.png">

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/9089131/172047928-ac90bada-cc6e-479a-be0b-d03a2e8bcbe3.png">

## Desktop (please complete the following information)

- OS: MacOS Monterey v: 12.0.1 (21A559)
- Versions (all that apply to bug): 
  - Dendron Extension: 0.97.0
  - VS Code version: 1.67.2
  - Dendron CLI:

## Additional context

These might be connected.

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here

```
{"level":30,"time":1654427027870,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1654427027919,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/Users/shivam/Library/Application Support/Code/logs/20220530T154648/exthost13/dendron.dendron","extensionPath":"/Users/shivam/.vscode/extensions/dendron.dendron-0.97.0","extensionUri":"/Users/shivam/.vscode/extensions/dendron.dendron-0.97.0","workspaceFile":"/Users/shivam/Dendron/dendron.code-workspace","workspaceFolders":["/Users/shivam/Dendron/MyNotes"]}
{"level":30,"time":1654427027940,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1654427027940,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1654427027940,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1654427027940,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1654427027940,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"anonymous id","anonymousId":"qTwidugLGFjqzfwonmsQO"}
{"level":30,"time":1654427027942,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1654427028219,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"CODE","currentVersion":"0.97.0","previousGlobalVersion":"0.97.0","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1654427028224,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1654427028224,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1654427028224,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1654427028224,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"anonymous id","anonymousId":"qTwidugLGFjqzfwonmsQO"}
{"level":30,"time":1654427028224,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","msg":"Telemetry is disabled? false"}
{"level":30,"time":1654427028225,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","msg":"Segment Residual Cache Path is at /Users/shivam/Library/Application Support/Code/User/globalStorage/dendron.dendron/segmentresidualcache.log"}
{"level":30,"time":1654427028225,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1654427028227,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"runMigrationsIfNecessary","changes":[],"workspaceInstallStatus":"NO_CHANGE"}
{"level":30,"time":1654427028232,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"_activate","platform":"darwin","extensions":[{"id":"dendron.dendron","version":"0.97.0","active":true},{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"redhat.vscode-yaml","version":"1.7.0","active":true}],"vaults":[{"fsPath":"MyNotes","name":"MyNotes"}]}
{"level":30,"time":1654427028234,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"execServer","state":"enter"}
{"level":30,"time":1654427028234,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1654427028991,"pid":56715,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1654427028991,"pid":56715,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"user telemetry setting: enabled by config"}
{"level":30,"time":1654427028991,"pid":56715,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"telemetry initializing"}
{"level":30,"time":1654427028991,"pid":56715,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"using existing id"}
{"level":30,"time":1654427028992,"pid":56715,"hostname":"Shivams-MacBook-Pro-2.local","name":"SegmentClient","msg":"anonymous id","anonymousId":"qTwidugLGFjqzfwonmsQO"}
{"level":30,"time":1654427029684,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"execServer","state":"message","message":"63425"}
{"level":30,"time":1654427029684,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WSUtils.handleServerProcess","msg":"subprocess running","pid":56715}
{"level":30,"time":1654427029684,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"startServerProcess","msg":"post-start-server","port":63425,"durationStartServer":1465}
{"level":30,"time":1654427029687,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: enter"}
{"level":30,"time":1654427029688,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree: exit"}
{"level":30,"time":1654427029713,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1654427029713,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1654427030100,"pid":56715,"hostname":"Shivams-MacBook-Pro-2.local","name":"logger","ctx":"parsingSchemas","fname":"article","root":{"fsPath":"MyNotes","name":"MyNotes"}}
{"level":30,"time":1654427030193,"pid":56715,"hostname":"Shivams-MacBook-Pro-2.local","name":"logger","ctx":"parsingSchemas","fname":"root","root":{"fsPath":"MyNotes","name":"MyNotes"},"imports":[]}
{"level":30,"time":1654427030430,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":519}
{"level":30,"time":1654427030431,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1654427030431,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1654427030434,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1654427030434,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1654427030434,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1654427030434,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1654427030434,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1654427030434,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1654427030489,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1654427030495,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"togglePluginActiveContext","state":"togglePluginActiveContext: true"}
{"level":30,"time":1654427030495,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"_activate","msg":"fin startClient","durationReloadWorkspace":2216}
{"level":30,"time":1654427030495,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.97.0","previousExtensionVersion":"0.90.0"}
{"level":30,"time":1654427045446,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","msg":"sendSavedAnalytics"}
{"level":30,"time":1654427045446,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"AnalyticsUtils.sendSavedAnalytics","message":"start"}
{"level":30,"time":1654427049342,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.publishExport:run","msg":"pre-execute"}
{"level":30,"time":1654427049342,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"PublishExportCommand","msg":"enter"}
{"level":30,"time":1654427050606,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"PublishExportCommand","msg":"prepare","enrichedOpts":{"podChoice":{"id":"dendron.nextjs","description":"export notes to Nextjs"},"config":{"dest":"/Users/shivam/Dendron/.next"}},"nextPath":"/Users/shivam/Dendron/.next"}
{"level":30,"time":1654427077569,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1654427077571,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1654427086717,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":{"ctx":"ExportPod"},"opts":{"podChoice":{"id":"dendron.nextjs","description":"export notes to Nextjs"},"config":{"dest":"/Users/shivam/Dendron/.next"},"quiet":true}}
{"level":30,"time":1654427086816,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427086853,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427086888,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427086938,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427086982,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087031,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087067,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087103,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087136,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087183,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087219,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087253,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087288,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087333,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087369,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087403,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087445,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087494,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087532,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087578,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087625,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087668,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087700,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087735,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087768,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087800,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427087832,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":50,"time":1654427091392,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.publishExport:run","error":{"name":"DendronError","status":"unknown","payload":"{}","innerError":{"shortMessage":"Command failed with exit code 1: npm run --silent export","command":"npm run --silent export","exitCode":1,"stdout":"info  - Loaded env from /Users/shivam/Dendron/.next/.env.production","stderr":"\n> Build error occurred\nError: Specified basePath has to start with a /, found \"MyNotes\"\n    at assignDefaults (/Users/shivam/Dendron/.next/node_modules/next/dist/server/config.js:170:19)\n    at Object.loadConfig [as default] (/Users/shivam/Dendron/.next/node_modules/next/dist/server/config.js:478:16)\n    at async Span.traceAsyncFn (/Users/shivam/Dendron/.next/node_modules/next/dist/trace/trace.js:75:20)\n    at async /Users/shivam/Dendron/.next/node_modules/next/dist/build/index.js:86:24\n    at async Span.traceAsyncFn (/Users/shivam/Dendron/.next/node_modules/next/dist/trace/trace.js:75:20)\n    at async Object.build [as default] (/Users/shivam/Dendron/.next/node_modules/next/dist/build/index.js:82:25)","failed":true,"timedOut":false,"isCanceled":false,"killed":false}}}
{"level":30,"time":1654427112555,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.configureRaw:run","msg":"pre-execute"}
{"level":30,"time":1654427112668,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/shivam/Dendron/dendron.yml"]}
{"level":30,"time":1654427112673,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1654427112678,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.configureRaw:run","msg":"post-execute"}
{"level":30,"time":1654427122748,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/shivam/Dendron/dendron.yml","reason":"Manual","msg":"enter"}
{"level":30,"time":1654427125024,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/shivam/Dendron/dendron.yml","reason":"Manual","msg":"enter"}
{"level":30,"time":1654427130574,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/shivam/Dendron/dendron.yml","reason":"Manual","msg":"enter"}
{"level":30,"time":1654427130777,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/Users/shivam/Dendron/dendron.yml","reason":"Manual","msg":"enter"}
{"level":30,"time":1654427133403,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.publishExport:run","msg":"pre-execute"}
{"level":30,"time":1654427133403,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"PublishExportCommand","msg":"enter"}
{"level":30,"time":1654427135109,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"PublishExportCommand","msg":"prepare","enrichedOpts":{"podChoice":{"id":"dendron.nextjs","description":"export notes to Nextjs"},"config":{"dest":"/Users/shivam/Dendron/.next"}},"nextPath":"/Users/shivam/Dendron/.next"}
{"level":30,"time":1654427163031,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":{"ctx":"ExportPod"},"opts":{"podChoice":{"id":"dendron.nextjs","description":"export notes to Nextjs"},"config":{"dest":"/Users/shivam/Dendron/.next"},"quiet":true}}
{"level":30,"time":1654427163088,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163135,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163184,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163219,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163249,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163285,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163320,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163354,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163392,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163440,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163518,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163545,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163584,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163620,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163654,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163684,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163721,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163753,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163787,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163820,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163854,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163887,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163918,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163953,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427163987,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427164018,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":30,"time":1654427164048,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksEngineNoteStateChanged"}
{"level":50,"time":1654427167271,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.publishExport:run","error":{"name":"DendronError","status":"unknown","payload":"{}","innerError":{"shortMessage":"Command failed with exit code 1: npm run --silent export","command":"npm run --silent export","exitCode":1,"stdout":"info  - Loaded env from /Users/shivam/Dendron/.next/.env.production","stderr":"\n> Build error occurred\nError: Specified basePath has to start with a /, found \"MyNotes\"\n    at assignDefaults (/Users/shivam/Dendron/.next/node_modules/next/dist/server/config.js:170:19)\n    at Object.loadConfig [as default] (/Users/shivam/Dendron/.next/node_modules/next/dist/server/config.js:478:16)\n    at async Span.traceAsyncFn (/Users/shivam/Dendron/.next/node_modules/next/dist/trace/trace.js:75:20)\n    at async /Users/shivam/Dendron/.next/node_modules/next/dist/build/index.js:86:24\n    at async Span.traceAsyncFn (/Users/shivam/Dendron/.next/node_modules/next/dist/trace/trace.js:75:20)\n    at async Object.build [as default] (/Users/shivam/Dendron/.next/node_modules/next/dist/build/index.js:82:25)","failed":true,"timedOut":false,"isCanceled":false,"killed":false}}}
{"level":30,"time":1654427562204,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.configureRaw:run","msg":"pre-execute"}
{"level":30,"time":1654427562219,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.configureRaw:run","msg":"post-execute"}
{"level":30,"time":1654427780194,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1654427780226,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1654427818761,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/Users/shivam/Dendron/dendron.yml"]}
{"level":30,"time":1654427818782,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1654427828906,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1654427828907,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1654427828916,"pid":56674,"hostname":"Shivams-MacBook-Pro-2.local","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
```

**Comment by SeriousBug** [comment]
Thanks for the report! Looks like the documentation was out of date, Dendron no longer has those commands. Please refer to the updated publishing documents here: https://wiki.dendron.so/notes/4ushYTDoX0TYQ1FDtGQSg/

Quickstart guide: https://wiki.dendron.so/notes/e5st4LFLtIwwbQmC6JBaF/

The warnings for the YAML are saying that it is missing some keys in your config. Dendron should prompt you at startup that you may be missing some configuration, if you accept the prompt it will fix the config.

I'll close this issue, but please let us know if you are still having issues. You can also join the [Discord](https://wiki.dendron.so/notes/bjhsGLyqME7QcNV6GueUb/) to get help quickly.
