### ISSUE TITLE
Publishing fails because `../custom/BannerAlert` is missing

### ISSUE THREAD

**Issue by dagriefaa** [dendronhq/dendron#3120]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Publishing crashes during type validation with this error:  `Type error: Cannot find module '../custom/BannerAlert' or its corresponding type declarations.`

## To Reproduce

1. Install Dendron CLI.
2. Run `npx dendron publish init`.
2. Run `npx dendron publish export`.
3. Observe crash.

## Expected behavior

Publishing does not crash.

## Desktop (please complete the following information)

- Dendron version: v0.100.0

## Build log
<details>
<summary>Click to expand</summary>

```
[0KRunning with gitlab-runner 15.1.0~beta.20.g62206bb2 (62206bb2)[0;m
[0K  on green-2.shared.runners-manager.gitlab.com/default ns46NMmJ[0;m
section_start:1655820080:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m[0;m
[0KUsing Docker executor with image node:14.16.0 ...[0;m
[0KPulling docker image node:14.16.0 ...[0;m
[0KUsing docker image sha256:abea835c0b3b0ef244d92a1076602ed0891a35b1b77fd73cd200a32860f822d5 for node:14.16.0 with digest node@sha256:f6b9ff4caca9d4f0a331a882e560df242eb332b7bbbed2f426784de208fcd7bd ...[0;m
section_end:1655820112:prepare_executor
[0Ksection_start:1655820112:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-ns46nmmj-project-34406112-concurrent-0 via runner-ns46nmmj-shared-1655820033-35107df5...
section_end:1655820115:prepare_script
[0Ksection_start:1655820115:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1m$ eval "$CI_PRE_CLONE_SCRIPT"[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Initialized empty Git repository in /builds/dagriefaa/publishing-with-nextjs/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out 4052c676 as main...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1655820116:get_sources
[0Ksection_start:1655820116:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:abea835c0b3b0ef244d92a1076602ed0891a35b1b77fd73cd200a32860f822d5 for node:14.16.0 with digest node@sha256:f6b9ff4caca9d4f0a331a882e560df242eb332b7bbbed2f426784de208fcd7bd ...[0;m
[32;1m$ npm init -y[0;m
Wrote to /builds/dagriefaa/publishing-with-nextjs/package.json:

{
  "name": "publishing-with-nextjs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://gitlab-ci-token:[MASKED]@gitlab.com/dagriefaa/publishing-with-nextjs.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://gitlab.com/dagriefaa/publishing-with-nextjs/issues"
  },
  "homepage": "https://gitlab.com/dagriefaa/publishing-with-nextjs#readme"
}


[32;1m$ npm install @dendronhq/dendron-cli[0;m
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated mdast@3.0.0: `mdast` was renamed to `remark`
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated libnpmconfig@1.2.1: This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config
npm WARN deprecated @types/airtable@0.10.1: This is a stub types definition. airtable provides its own type definitions, so you do not need this installed.
npm WARN deprecated @instantish/martian@1.0.3: Please use @tryfabric/martian instead
npm WARN deprecated @types/node-fetch@3.0.3: This is a stub types definition. node-fetch provides its own type definitions, so you do not need this installed.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN publishing-with-nextjs@1.0.0 No description

+ @dendronhq/dendron-cli@0.100.0
added 626 packages from 469 contributors and audited 627 packages in 44.94s

149 packages are looking for funding
  run `npm fund` for details

found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
[32;1m$ npx dendron publish init[0;m

===================
Telemetry notice ðŸŒ±
===================
Dendron collects limited usage data to help improve the quality of our software.

You can learn everything about our telemetry policies by visiting the following link: 
https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html

If you would like to opt out, follow the instructions below: 
https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html#how-to-opt-out-of-data-collection
ðŸŒ± checking if .next directory exists.
ðŸŒ± .next directory does not exist
ðŸŒ± Initializing NextJS template.
- Cloning NextJS template...
ðŸŒ± Successfully cloned.
- Cloning NextJS template...
- Installing dependencies... This may take a while.
ðŸŒ± All dependencies installed.
- Installing dependencies... This may take a while.
[32;1m$ npx dendron publish export[0;m
ðŸŒ± checking if NextJS template is initialized
ðŸŒ± NextJS template is already initialized.
generating metadata for publishing...

> @dendronhq/nextjs-template@0.100.0 export /builds/dagriefaa/publishing-with-nextjs/.next
> next build && next export

info  - Loaded env from /builds/dagriefaa/publishing-with-nextjs/.next/.env.production
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Checking validity of types...
{"level":50,"time":1655820259713,"pid":71,"hostname":"runner-ns46nmmj-project-34406112-concurrent-0","name":"publish <cmd>","shortMessage":"Command failed with exit code 1: npm run export","command":"npm run export","exitCode":1,"stdout":"\n> @dendronhq/nextjs-template@0.100.0 export /builds/dagriefaa/publishing-with-nextjs/.next\n> next build && next export\n\ninfo  - Loaded env from /builds/dagriefaa/publishing-with-nextjs/.next/.env.production\nwarn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache\nAttention: Next.js now collects completely anonymous telemetry regarding usage.\nThis information is used to shape Next.js' roadmap and prioritize features.\nYou can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:\nhttps://nextjs.org/telemetry\n\ninfo  - Checking validity of types...","stderr":"Failed to compile.\n\n./components/DendronNotePage.tsx:62:44\nType error: Cannot find module '../custom/BannerAlert' or its corresponding type declarations.\n\n\u001b[0m \u001b[90m 60 | \u001b[39m      \u001b[36mtry\u001b[39m {\u001b[0m\n\u001b[0m \u001b[90m 61 | \u001b[39m        \u001b[90m// eslint-disable-next-line global-require\u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 62 | \u001b[39m        \u001b[33mBannerAlert\u001b[39m \u001b[33m=\u001b[39m dynamic(() \u001b[33m=>\u001b[39m \u001b[36mimport\u001b[39m(\u001b[32m\"../custom/BannerAlert\"\u001b[39m)\u001b[33m,\u001b[39m {\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m                                           \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 63 | \u001b[39m          loading\u001b[33m:\u001b[39m () \u001b[33m=>\u001b[39m \u001b[36mnull\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 64 | \u001b[39m        })\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 65 | \u001b[39m        \u001b[90m// eslint-disable-next-line no-empty\u001b[39m\u001b[0m\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @dendronhq/nextjs-template@0.100.0 export: `next build && next export`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @dendronhq/nextjs-template@0.100.0 export script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2022-06-21T14_04_19_692Z-debug.log","failed":true,"timedOut":false,"isCanceled":false,"killed":false,"stack":"Error: Command failed with exit code 1: npm run export\nFailed to compile.\n\n./components/DendronNotePage.tsx:62:44\nType error: Cannot find module '../custom/BannerAlert' or its corresponding type declarations.\n\n\u001b[0m \u001b[90m 60 | \u001b[39m      \u001b[36mtry\u001b[39m {\u001b[0m\n\u001b[0m \u001b[90m 61 | \u001b[39m        \u001b[90m// eslint-disable-next-line global-require\u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 62 | \u001b[39m        \u001b[33mBannerAlert\u001b[39m \u001b[33m=\u001b[39m dynamic(() \u001b[33m=>\u001b[39m \u001b[36mimport\u001b[39m(\u001b[32m\"../custom/BannerAlert\"\u001b[39m)\u001b[33m,\u001b[39m {\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m                                           \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 63 | \u001b[39m          loading\u001b[33m:\u001b[39m () \u001b[33m=>\u001b[39m \u001b[36mnull\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 64 | \u001b[39m        })\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 65 | \u001b[39m        \u001b[90m// eslint-disable-next-line no-empty\u001b[39m\u001b[0m\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @dendronhq/nextjs-template@0.100.0 export: `next build && next export`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @dendronhq/nextjs-template@0.100.0 export script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2022-06-21T14_04_19_692Z-debug.log\n\n> @dendronhq/nextjs-template@0.100.0 export /builds/dagriefaa/publishing-with-nextjs/.next\n> next build && next export\n\ninfo  - Loaded env from /builds/dagriefaa/publishing-with-nextjs/.next/.env.production\nwarn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache\nAttention: Next.js now collects completely anonymous telemetry regarding usage.\nThis information is used to shape Next.js' roadmap and prioritize features.\nYou can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:\nhttps://nextjs.org/telemetry\n\ninfo  - Checking validity of types...\n    at makeError (/builds/dagriefaa/publishing-with-nextjs/node_modules/@dendronhq/engine-server/node_modules/execa/lib/error.js:59:11)\n    at handlePromise (/builds/dagriefaa/publishing-with-nextjs/node_modules/@dendronhq/engine-server/node_modules/execa/index.js:114:26)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async PublishCLICommand.export (/builds/dagriefaa/publishing-with-nextjs/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:396:9)\n    at async PublishCLICommand.execute (/builds/dagriefaa/publishing-with-nextjs/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:159:21)\n    at async Object.CLICommand.eval [as handler] (/builds/dagriefaa/publishing-with-nextjs/node_modules/@dendronhq/dendron-cli/lib/src/commands/base.js:58:25)","type":"Error","msg":"Command failed with exit code 1: npm run export\nFailed to compile.\n\n./components/DendronNotePage.tsx:62:44\nType error: Cannot find module '../custom/BannerAlert' or its corresponding type declarations.\n\n\u001b[0m \u001b[90m 60 | \u001b[39m      \u001b[36mtry\u001b[39m {\u001b[0m\n\u001b[0m \u001b[90m 61 | \u001b[39m        \u001b[90m// eslint-disable-next-line global-require\u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 62 | \u001b[39m        \u001b[33mBannerAlert\u001b[39m \u001b[33m=\u001b[39m dynamic(() \u001b[33m=>\u001b[39m \u001b[36mimport\u001b[39m(\u001b[32m\"../custom/BannerAlert\"\u001b[39m)\u001b[33m,\u001b[39m {\u001b[0m\n\u001b[0m \u001b[90m    | \u001b[39m                                           \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 63 | \u001b[39m          loading\u001b[33m:\u001b[39m () \u001b[33m=>\u001b[39m \u001b[36mnull\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 64 | \u001b[39m        })\u001b[33m;\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 65 | \u001b[39m        \u001b[90m// eslint-disable-next-line no-empty\u001b[39m\u001b[0m\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @dendronhq/nextjs-template@0.100.0 export: `next build && next export`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @dendronhq/nextjs-template@0.100.0 export script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2022-06-21T14_04_19_692Z-debug.log\n\n> @dendronhq/nextjs-template@0.100.0 export /builds/dagriefaa/publishing-with-nextjs/.next\n> next build && next export\n\ninfo  - Loaded env from /builds/dagriefaa/publishing-with-nextjs/.next/.env.production\nwarn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache\nAttention: Next.js now collects completely anonymous telemetry regarding usage.\nThis information is used to shape Next.js' roadmap and prioritize features.\nYou can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:\nhttps://nextjs.org/telemetry\n\ninfo  - Checking validity of types..."}
unknown error [object Object]
[32;1m$ mv .next/out public[0;m
mv: cannot stat '.next/out': No such file or directory
section_end:1655820270:step_script
[0Ksection_start:1655820270:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1655820271:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```
</details>

## Additional context

- [Github example repo](https://github.com/dagriefaa/publishing-with-nextjs)
- [Gitlab example repo](https://gitlab.com/dagriefaa/publishing-with-nextjs)

**Comment by jonathanyeung** [comment]
Thanks for the report @dagriefaa - it looks like we broke something with the v100 of the nextjs template.  We've just reverted it - can you try again now?  If you run the same command sequence, it should pick up the reverted version.
