### ISSUE TITLE
Conflict occurred while exporting to Notion

### ISSUE THREAD

**Issue by l2dy** [dendronhq/dendron#3269]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [x] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I could not export a hierarchy of notes to Notion.

```
DendronError: Failed to export all the notes. {"code":"conflict_error","name":"APIResponseError","status":409,"headers":{REDACTED},"body":"{"object":"error","status":409,"code":"conflict_error","message":"Conflict occurred while saving. Please try again."}"}
    at /Users/<user>/.vscode/extensions/dendron.dendron-0.104.0/dist/extension.js:2:673203
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
    at async d.plant (/Users/<user>/.vscode/extensions/dendron.dendron-0.104.0/dist/extension.js:2:674751)
    at async d.execute (/Users/<user>/.vscode/extensions/dendron.dendron-0.104.0/dist/extension.js:2:616579)
    at async jr.execute (/Users/<user>/.vscode/extensions/dendron.dendron-0.104.0/dist/extension.js:8:3220069)
    at async jr.run (/Users/<user>/.vscode/extensions/dendron.dendron-0.104.0/dist/extension.js:8:2992191)
    at async /Users/<user>/.vscode/extensions/dendron.dendron-0.104.0/dist/extension.js:8:3425887
    at async o._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:62513)
```

## To Reproduce

1. Run 'Dendron: Export Pod'
2. See error

## Expected behavior

Pod export successfully completes.

## Screenshots

N/A

## Desktop (please complete the following information)

- OS: macOS
- Versions (all that apply to bug):
  - Dendron Extension: 0.104.0
  - VS Code version: 1.68.1
  - Dendron CLI: 0.103.0

## Additional context

Vault exported is https://github.com/l2dy/kb.

**Comment by Harshita-mindfire** [comment]
Thank you for raising the bug report. We will inform you when this gets fixed

**Comment by renanbronchart** [comment]
I have the same error.
Do you have any update on this?

**Comment by rong-z** [comment]
I have the same error.
Do you have any update on this?

**Comment by l2dy** [comment]
Given that Dendron the project is now in maintenance mode, I do not expect a fix for this issue anytime soon.
