### ISSUE TITLE
Publishing is broken.

### ISSUE THREAD

**Issue by nickolay-kondratyev** [dendronhq/dendron#3665]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Using the latest CLI 115.0 https://www.npmjs.com/package/@dendronhq/dendron-cli confirmed with npm list. 

States this error. 
```
The version of `dendron-cli` you have is out of date
```

## To Reproduce

```
> pwd
/var/ForPublish
> rm -rf .next/
> npm list
ForPublish@ /var/ForPublish
└── @dendronhq/dendron-cli@0.115.0

> npx dendron publish init
🌱 checking if .next directory exists.
🌱 .next directory does not exist
🌱 Initializing NextJS template.
🌱 Successfully cloned.
🌱 All dependencies installed.
> npx dendron publish export
🌱 checking if NextJS template is initialized
🌱 NextJS template is already initialized.
⠋ generating metadata for publishing...

> @dendronhq/nextjs-template@0.115.0 export
> npm run build && next export


> @dendronhq/nextjs-template@0.115.0 build
> npm run copy:robotstxt && next build


> @dendronhq/nextjs-template@0.115.0 copy:robotstxt
> npx cpx assets/robots.txt public/

info  - Loaded env from /var/ForPublish/.next/.env.production
{"level":50,"time":1665624510732,"pid":27620,"name":"publish <cmd>","shortMessage":"Command failed with exit code 1: npm run export","command":"npm run export","exitCode":1,"stdout":"\n> @dendronhq/nextjs-template@0.115.0 export\n> npm run build && next export\n\n\n> @dendronhq/nextjs-template@0.115.0 build\n> npm run copy:robotstxt && next build\n\n\n> @dendronhq/nextjs-template@0.115.0 copy:robotstxt\n> npx cpx assets/robots.txt public/\n\ninfo  - Loaded env from /var/ForPublish/.next/.env.production","stderr":"error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error\n\n> Build error occurred\nError: The version of `dendron-cli` you have is out of date and not compatible with the latest nextjs-template. Please upgrade you `dendron-cli` by running `npm install @dendron-cli@latest` in the root of your workspace (where your dendron.yml file is located).\n    at Object.<anonymous> (/var/ForPublish/.next/utils/validation.js:15:9)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/ForPublish/.next/next.config.js:4:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)","failed":true,"timedOut":false,"isCanceled":false,"killed":false,"stack":"Error: Command failed with exit code 1: npm run export\nerror - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error\n\n> Build error occurred\nError: The version of `dendron-cli` you have is out of date and not compatible with the latest nextjs-template. Please upgrade you `dendron-cli` by running `npm install @dendron-cli@latest` in the root of your workspace (where your dendron.yml file is located).\n    at Object.<anonymous> (/var/ForPublish/.next/utils/validation.js:15:9)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/ForPublish/.next/next.config.js:4:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n\n> @dendronhq/nextjs-template@0.115.0 export\n> npm run build && next export\n\n\n> @dendronhq/nextjs-template@0.115.0 build\n> npm run copy:robotstxt && next build\n\n\n> @dendronhq/nextjs-template@0.115.0 copy:robotstxt\n> npx cpx assets/robots.txt public/\n\ninfo  - Loaded env from /var/ForPublish/.next/.env.production\n    at makeError (/var/ForPublish/node_modules/@dendronhq/engine-server/node_modules/execa/lib/error.js:59:11)\n    at handlePromise (/var/ForPublish/node_modules/@dendronhq/engine-server/node_modules/execa/index.js:114:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PublishCLICommand.export (/var/ForPublish/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:408:9)\n    at async PublishCLICommand.execute (/var/ForPublish/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:171:21)\n    at async Object.CLICommand.eval [as handler] (/var/ForPublish/node_modules/@dendronhq/dendron-cli/lib/src/commands/base.js:58:25)","type":"Error","msg":"Command failed with exit code 1: npm run export\nerror - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error\n\n> Build error occurred\nError: The version of `dendron-cli` you have is out of date and not compatible with the latest nextjs-template. Please upgrade you `dendron-cli` by running `npm install @dendron-cli@latest` in the root of your workspace (where your dendron.yml file is located).\n    at Object.<anonymous> (/var/ForPublish/.next/utils/validation.js:15:9)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n    at Module.load (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/var/ForPublish/.next/next.config.js:4:1)\n    at Module._compile (node:internal/modules/cjs/loader:1105:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)\n\n> @dendronhq/nextjs-template@0.115.0 export\n> npm run build && next export\n\n\n> @dendronhq/nextjs-template@0.115.0 build\n> npm run copy:robotstxt && next build\n\n\n> @dendronhq/nextjs-template@0.115.0 copy:robotstxt\n> npx cpx assets/robots.txt public/\n\ninfo  - Loaded env from /var/ForPublish/.next/.env.production"}
unknown error [object Object]

```

## Expected behavior

Web pages are published. 

## Desktop (please complete the following information)
  - Dendron CLI: 115.0

**Comment by kevinslin** [comment]
the reason your seeing this is because version 0.115 of the `nextjs-template` requires some additional json files that are generated by the newer version of the `dendron-cli`. to fix this, you'll want to run the following in the repo where your site is located

```
npm install @dendronhq/dendron-cli@latest 
```

**Comment by kevinslin** [comment]
hmm, so the reason you're seeing this is because we've changed the structure of one of the json files used to generated the tree view: https://github.com/dendronhq/nextjs-template/blob/main/utils/validation.js#L12:L12

can you verify that the `tree.json` generated by the cli has the following keys?

```sh
cat .next/data/tree.json | jq ".|keys"
[
  "child2parent",
  "notesLabelById",
  "roots"
]
```

**Comment by nickolay-kondratyev** [comment]
Yes it does appear to have it, after attempting to run `dendron publish export` (which fails). 

```
> cat .next/data/tree.json | jq ".|keys"
[
  "child2parent",
  "notesLabelById",
  "roots"
]
```

**Comment by kevinslin** [comment]
hmm, are you able to share the contents of `tree.json`? 
the validation checks for the following field: https://github.com/dendronhq/dendron/blob/master/packages/common-all/src/util/treeUtil.ts#L30:L30


meanwhile, if you want to publish to work, you can go to `cd .next && git checkout 0333e1a` to go back to before this check was in place

**Comment by nickolay-kondratyev** [comment]
Thank you for suggestion to try out.

Trying out
```
git checkout 0333e1a
```

in `.next` 


still causes 
```
npx dendron publish export
```

To fail with the following error: (glh=git log | head)
```
> cd .next
> glh
* e8c67af - (33 hours ago) sync - Kevin (origin/main, origin/HEAD, main)
* 222406b - (33 hours ago) sync - Kevin
* 23c7238 - (34 hours ago) add lodash - Kevin
* 8e47645 - (34 hours ago) update cpx cmd - Kevin
* 4a20d1b - (35 hours ago) chore(release): sync nextjs-template with dendron 0.115.0 - Mark Choi (origin/dev)
* 7236786 - (2 days ago) chore(release): sync nextjs-template with dendron 0.115.0 - Mark Choi
* 0333e1a - (2 weeks ago) update lockfile - Kevin (HEAD -> revert)
>
> cd ..
> npx dendron publish export
<\u001b[39m\u001b[33mBannerAlert\u001b[39m \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m}\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 122 | \u001b[39m              \u001b[33m<\u001b[39m\u001b[33mDendronNote\u001b[39m noteContent\u001b[33m=\u001b[39m{noteBody} config\u001b[33m=\u001b[39m{config} \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m     | \u001b[39m                                                  \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 123 | \u001b[39m              {maybeCollection}\u001b[0m\n\u001b[0m \u001b[90m 124 | \u001b[39m              \u001b[33m<\u001b[39m\u001b[33mDendronNoteGiscusWidget\u001b[39m note\u001b[33m=\u001b[39m{note} config\u001b[33m=\u001b[39m{config} \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 125 | \u001b[39m            \u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33mCol\u001b[39m\u001b[33m>\u001b[39m\u001b[0m","failed":true,"timedOut":false,"isCanceled":false,"killed":false,"stack":"Error: Command failed with exit code 1: npm run export\nFailed to compile.\n\n./components/DendronNotePage.tsx:122:51\nType error: Type '{ noteContent: string; config: IntermediateDendronConfig; }' is not assignable to type 'IntrinsicAttributes & Props'.\n  Property 'config' does not exist on type 'IntrinsicAttributes & Props'.\n\n\u001b[0m \u001b[90m 120 | \u001b[39m            \u001b[33m<\u001b[39m\u001b[33mCol\u001b[39m xs\u001b[33m=\u001b[39m{\u001b[35m24\u001b[39m} md\u001b[33m=\u001b[39m{\u001b[35m18\u001b[39m}\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 121 | \u001b[39m              {\u001b[33mBannerAlert\u001b[39m \u001b[33m&&\u001b[39m \u001b[33m<\u001b[39m\u001b[33mBannerAlert\u001b[39m \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m}\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 122 | \u001b[39m              \u001b[33m<\u001b[39m\u001b[33mDendronNote\u001b[39m noteContent\u001b[33m=\u001b[39m{noteBody} config\u001b[33m=\u001b[39m{config} \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m     | \u001b[39m                                                  \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 123 | \u001b[39m              {maybeCollection}\u001b[0m\n\u001b[0m \u001b[90m 124 | \u001b[39m              \u001b[33m<\u001b[39m\u001b[33mDendronNoteGiscusWidget\u001b[39m note\u001b[33m=\u001b[39m{note} config\u001b[33m=\u001b[39m{config} \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 125 | \u001b[39m            \u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33mCol\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\n> @dendronhq/nextjs-template@0.111.0 export\n> next build && next export\n\ninfo  - Loaded env from /var/ForPublish/.next/.env.production\ninfo  - Linting and checking validity of types...\n    at makeError (/var/ForPublish/node_modules/@dendronhq/engine-server/node_modules/execa/lib/error.js:59:11)\n    at handlePromise (/var/ForPublish/node_modules/@dendronhq/engine-server/node_modules/execa/index.js:114:26)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PublishCLICommand.export (/var/ForPublish/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:408:9)\n    at async PublishCLICommand.execute (/var/ForPublish/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:171:21)\n    at async Object.CLICommand.eval [as handler] (/var/ForPublish/node_modules/@dendronhq/dendron-cli/lib/src/commands/base.js:58:25)","type":"Error","msg":"Command failed with exit code 1: npm run export\nFailed to compile.\n\n./components/DendronNotePage.tsx:122:51\nType error: Type '{ noteContent: string; config: IntermediateDendronConfig; }' is not assignable to type 'IntrinsicAttributes & Props'.\n  Property 'config' does not exist on type 'IntrinsicAttributes & Props'.\n\n\u001b[0m \u001b[90m 120 | \u001b[39m            \u001b[33m<\u001b[39m\u001b[33mCol\u001b[39m xs\u001b[33m=\u001b[39m{\u001b[35m24\u001b[39m} md\u001b[33m=\u001b[39m{\u001b[35m18\u001b[39m}\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 121 | \u001b[39m              {\u001b[33mBannerAlert\u001b[39m \u001b[33m&&\u001b[39m \u001b[33m<\u001b[39m\u001b[33mBannerAlert\u001b[39m \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m}\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 122 | \u001b[39m              \u001b[33m<\u001b[39m\u001b[33mDendronNote\u001b[39m noteContent\u001b[33m=\u001b[39m{noteBody} config\u001b[33m=\u001b[39m{config} \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m     | \u001b[39m                                                  \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 123 | \u001b[39m              {maybeCollection}\u001b[0m\n\u001b[0m \u001b[90m 124 | \u001b[39m              \u001b[33m<\u001b[39m\u001b[33mDendronNoteGiscusWidget\u001b[39m note\u001b[33m=\u001b[39m{note} config\u001b[33m=\u001b[39m{config} \u001b[33m/\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 125 | \u001b[39m            \u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33mCol\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\n> @dendronhq/nextjs-template@0.111.0 export\n> next build && next export\n\ninfo  - Loaded env from /var/ForPublish/.next/.env.production\ninfo  - Linting and checking validity of types..."}
unknown error [object Object]
```

**Comment by nickolay-kondratyev** [comment]
Something must be off with my repo, Setting it back some commits back fixes the issue. Will look for what caused it likely tomorrow.

**Comment by nickolay-kondratyev** [comment]
Looks like it was due to a missing `id` value in one of the notes

Note looked like

```
---
id: 
title: some-title
...
```

Would be good to improvement to add validation of this and fail publishing with an appropriate message.

**Comment by kevinslin** [comment]
Ah - glad you got to the bottom of this. We've recently added validation
for issues with the `dendron.yml` - will also validate on the notes side as
well

**Comment by nickolay-kondratyev** [comment]
Note empty title field (without '') 

Such as:

```
title: 
```

Also appears to trigger such behavior.
