### ISSUE TITLE
Error when npx dendron publish export

### ISSUE THREAD

**Issue by KitLeskinen** [dendronhq/dendron#3696]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Command _npx dendron publish export_ not working

## To Reproduce

```bash
[dendron@dendron dendron]$ ls
dendron.code-workspace  dendron.yml  diagram-dendron.svg  node_modules  notes  package.json  package-lock.json
[dendron@dendron dendron]$ npx dendron publish init
🌱 checking if .next directory exists.
🌱 .next directory exists
🌱 updating NextJS template.
🌱 All dependencies installed.
🌱 updated NextJS template.
[dendron@dendron dendron]$ npm list
dendron@ /home/dendron/dendron
└── @dendronhq/dendron-cli@0.115.1

[dendron@dendron dendron]$ npx dendron publish export
🌱 checking if NextJS template is initialized
🌱 NextJS template is already initialized.
⠋ generating metadata for publishing...
⠙ Error: connect ECONNREFUSED 127.0.0.1:45793
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 45793,
  config: {
    url: 'http://localhost:45793/api/workspace/initialize?',
    method: 'post',
    data: '{"uri":"/home/dendron/dendron","config":{"vaults":[{"fsPath":".","selfContained":true,"name":"dendron"}]}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 106
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/workspace/initialize?',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '45793',
      nativeProtocols: [Object],
      pathname: '/api/workspace/initialize',
      search: '?'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 106,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/workspace/initialize? HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 106\r\n' +
        'Host: localhost:45793\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/workspace/initialize?',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:45793/api/workspace/initialize?',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
Error: connect ECONNREFUSED 127.0.0.1:45793
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 45793,
  config: {
    url: 'http://localhost:45793/api/workspace/initialize?',
    method: 'post',
    data: '{"uri":"/home/dendron/dendron","config":{"vaults":[{"fsPath":".","selfContained":true,"name":"dendron"}]}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 106
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/workspace/initialize?',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '45793',
      nativeProtocols: [Object],
      pathname: '/api/workspace/initialize',
      search: '?'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 106,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/workspace/initialize? HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 106\r\n' +
        'Host: localhost:45793\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/workspace/initialize?',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:45793/api/workspace/initialize?',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
⠹ error {"stack":"TypeError: Cannot read properties of undefined (reading 'map')\n    at SiteUtils.filterByHierarchy (/home/dendron/dendron/node_modules/@dendronhq/engine-server/lib/topics/site.js:181:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/dendron/dendron/node_modules/@dendronhq/engine-server/lib/topics/site.js:123:25\n    at async Promise.all (index 0)\n    at async SiteUtils.filterByConfig (/home/dendron/dendron/node_modules/@dendronhq/engine-server/lib/topics/site.js:122:47)\n    at async NextjsExportPod.plant (/home/dendron/dendron/node_modules/@dendronhq/pods-core/lib/builtin/NextjsExportPod.js:366:52)\n    at async NextjsExportPod.execute (/home/dendron/dendron/node_modules/@dendronhq/pods-core/lib/basev3.js:103:20)\n    at async ExportPodCLICommand.execute (/home/dendron/dendron/node_modules/@dendronhq/dendron-cli/lib/src/commands/exportPod.js:34:9)\n    at async PublishCLICommand._buildNextData (/home/dendron/dendron/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:222:24)\n    at async PublishCLICommand.build (/home/dendron/dendron/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:384:27)","message":"Cannot read properties of undefined (reading 'map')"}
{"level":50,"time":1666265863454,"pid":6471,"hostname":"dendron","name":"publish <cmd>","stack":"TypeError: Cannot read properties of undefined (reading 'map')\n    at SiteUtils.filterByHierarchy (/home/dendron/dendron/node_modules/@dendronhq/engine-server/lib/topics/site.js:181:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/dendron/dendron/node_modules/@dendronhq/engine-server/lib/topics/site.js:123:25\n    at async Promise.all (index 0)\n    at async SiteUtils.filterByConfig (/home/dendron/dendron/node_modules/@dendronhq/engine-server/lib/topics/site.js:122:47)\n    at async NextjsExportPod.plant (/home/dendron/dendron/node_modules/@dendronhq/pods-core/lib/builtin/NextjsExportPod.js:366:52)\n    at async NextjsExportPod.execute (/home/dendron/dendron/node_modules/@dendronhq/pods-core/lib/basev3.js:103:20)\n    at async ExportPodCLICommand.execute (/home/dendron/dendron/node_modules/@dendronhq/dendron-cli/lib/src/commands/exportPod.js:34:9)\n    at async PublishCLICommand._buildNextData (/home/dendron/dendron/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:222:24)\n    at async PublishCLICommand.build (/home/dendron/dendron/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:384:27)","type":"Error","msg":"Cannot read properties of undefined (reading 'map')"}
unknown error [object Object]
```

## Expected behavior

Publish is working

## Desktop (please complete the following information)

- CentOS Stream 8
- Versions (all that apply to bug):
  - Dendron Extension: 0 .115.1
  - VS Code version: 1.72.2
  - Dendron CLI: 0.115.1

## Additional context

Same commands work on Windows 10
Selinux disabled
Firewalld disabled

**Comment by Harshita-mindfire** [comment]
Thanks @KitLeskinen for the bug report. From the error it looks like the `siteHierarchies` field under `publishing` namespace is not set in the `dendron.yml` file. Can you run `Dendron: Configure(yaml)` or `Dendron: Configure(UI) and see that the publishing.siteHierarchies config option is defined?

**Comment by KitLeskinen** [comment]
I tried to run a freshly initialized clean project with no changes and got the same result

```bash
[dendron@dendron dendron_test2]$ npx dendron publish init
🌱 checking if .next directory exists.
🌱 .next directory does not exist
🌱 Initializing NextJS template.
🌱 Successfully cloned.
🌱 All dependencies installed.
[dendron@dendron dendron_test2]$ npx dendron publish export
🌱 checking if NextJS template is initialized
🌱 NextJS template is already initialized.
⠋ generating metadata for publishing...
⠙ Error: connect ECONNREFUSED 127.0.0.1:36049
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 36049,
  config: {
    url: 'http://localhost:36049/api/workspace/initialize?',
    method: 'post',
    data: '{"uri":"/home/dendron/dendron_test2","config":{"vaults":[{"fsPath":".","selfContained":true,"name":"dendron_test2"}]}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 118
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/workspace/initialize?',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '36049',
      nativeProtocols: [Object],
      pathname: '/api/workspace/initialize',
      search: '?'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 118,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/workspace/initialize? HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 118\r\n' +
        'Host: localhost:36049\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/workspace/initialize?',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:36049/api/workspace/initialize?',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
Error: connect ECONNREFUSED 127.0.0.1:36049
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 36049,
  config: {
    url: 'http://localhost:36049/api/workspace/initialize?',
    method: 'post',
    data: '{"uri":"/home/dendron/dendron_test2","config":{"vaults":[{"fsPath":".","selfContained":true,"name":"dendron_test2"}]}}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 118
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    }
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/workspace/initialize?',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '36049',
      nativeProtocols: [Object],
      pathname: '/api/workspace/initialize',
      search: '?'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 118,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /api/workspace/initialize? HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 118\r\n' +
        'Host: localhost:36049\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/workspace/initialize?',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:36049/api/workspace/initialize?',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
⠹ error {"stack":"TypeError: Cannot read properties of undefined (reading 'map')\n    at SiteUtils.filterByHierarchy (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:181:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:123:25\n    at async Promise.all (index 0)\n    at async SiteUtils.filterByConfig (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:122:47)\n    at async NextjsExportPod.plant (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/builtin/NextjsExportPod.js:366:52)\n    at async NextjsExportPod.execute (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/basev3.js:103:20)\n    at async ExportPodCLICommand.execute (/usr/local/lib/node_modules/@dendronhq/dendron-cli/lib/src/commands/exportPod.js:34:9)\n    at async PublishCLICommand._buildNextData (/usr/local/lib/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:222:24)\n    at async PublishCLICommand.build (/usr/local/lib/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:384:27)","message":"Cannot read properties of undefined (reading 'map')"}
{"level":50,"time":1666607824503,"pid":2159,"hostname":"dendron","name":"publish <cmd>","stack":"TypeError: Cannot read properties of undefined (reading 'map')\n    at SiteUtils.filterByHierarchy (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:181:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:123:25\n    at async Promise.all (index 0)\n    at async SiteUtils.filterByConfig (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:122:47)\n    at async NextjsExportPod.plant (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/builtin/NextjsExportPod.js:366:52)\n    at async NextjsExportPod.execute (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/basev3.js:103:20)\n    at async ExportPodCLICommand.execute (/usr/local/lib/node_modules/@dendronhq/dendron-cli/lib/src/commands/exportPod.js:34:9)\n    at async PublishCLICommand._buildNextData (/usr/local/lib/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:222:24)\n    at async PublishCLICommand.build (/usr/local/lib/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:384:27)","type":"Error","msg":"Cannot read properties of undefined (reading 'map')"}
unknown error [object Object]
```

dendron.yml:
[dendron.txt](https://github.com/dendronhq/dendron/files/9850998/dendron.txt)
