### ISSUE TITLE
importPod fails w/ 'TypeError: Cannot read property 'custom' of undefined' if directory ends w/ '.md'

### ISSUE THREAD

**Issue by karstengresch** [dendronhq/dendron#3702]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [x] Pod.  Data import from / export to Dendron
- [ ] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

When running ```dendron importPod``` on a directory that has a name ending with ".md", dendron crashes with an error message like

```
TypeError: Cannot read property 'custom' of undefined
    at /usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/builtin/MarkdownPod.js:208:42
    at Array.forEach (<anonymous>)
    at MarkdownImportPod.hDict2Notes (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/builtin/MarkdownPod.js:205:26)
    at MarkdownImportPod.plant (/usr/local/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/builtin/MarkdownPod.js:343:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ImportPodCLICommand.execute (/usr/local/lib/node_modules/@dendronhq/dendron-cli/lib/src/commands/importPod.js:36:9)
    at async Object.CLICommand.eval [as handler] (/usr/local/lib/node_modules/@dendronhq/dendron-cli/lib/src/commands/base.js:58:25)
```

## To Reproduce

```bash
mkdir test.md
cd test.md
touch test01.md
echo "# Header 1 \n\n ## Header 2 \nThis is just for testing." > test01.md
dendron importPod --podId dendron.markdown --wsRoot #your root here
```

## Expected behavior

Dendron shall either import the directory or fail with an error message that it cannot import directories ending with ".md".

## Desktop (please complete the following information)

- OS: macOS 12.4
- Browser N/A
- Versions 
  - Dendron Extension: 0.115.1
  - VS Code version: VSCodium 1.71.2
  - Dendron CLI: 0.115.1

## Dendron Log file

Please attach the output of `> Dendron:Dev: Open Logs` here => N/A

**Comment by Harshita-mindfire** [comment]
Thanks for reporting the bug. I can repro this. We will update you when this gets fixed 🙏
