### ISSUE TITLE
Can't build Dendron Site

### ISSUE THREAD

**Issue by dentropy** [dendronhq/dendron#3774]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [X] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Running `npx dendron publish export` permanently hangs with an error of some kind seen below

## To Reproduce

* I install dendron 0.117.0 in vscode
* I create fresh workspace
* I add vault, https://gitlab.com/dentropy/dentropydaemon-wiki , via SSH, it clones sucessfully (you can use https)
* I install dendron cli 0.117.0
* I set siteURL in dendron.yml
* I run `npx dendron publish init`, runs sucessfully
* I run `npx dendron publish export` and I get the following error
* I get error below

## Expected behavior

I expect for my site to be built in the .next folder

## Desktop (please complete the following information)

- OS: POPOS 20.04
- Versions (all that apply to bug): 0.117.0
  - Dendron Extension: 0.117.0
  - VS Code version: Codium 1.73.0
  - Dendron CLI: 0.117.0

## Additional context

I also tried buildSiteV2 from dendron-cli@0.70.0 with no sucesses, also rebuilt dendron.yml accordingly

## Dendron Log file

``` bash 
$ dendron publish export
🌱 checking if NextJS template is initialized
🌱 NextJS template is already initialized.
⠋ generating metadata for publishing...
⠏ error {"stack":"TypeError: Cannot read properties of undefined (reading 'custom')\n    at SiteUtils.canPublish (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:23:25)\n    at /home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:268:78\n    at arrayFilter (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/lodash/lodash.js:596:11)\n    at Function.filter (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/lodash/lodash.js:9241:14)\n    at SiteUtils.filterByHierarchy (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:268:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:121:25\n    at async Promise.all (index 0)\n    at async SiteUtils.filterByConfig (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:120:47)\n    at async NextjsExportPod.plant (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/builtin/NextjsExportPod.js:356:52)","message":"Cannot read properties of undefined (reading 'custom')"}
{"level":50,"time":1668047862015,"pid":253058,"hostname":"pop-os","name":"publish <cmd>","stack":"TypeError: Cannot read properties of undefined (reading 'custom')\n    at SiteUtils.canPublish (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:23:25)\n    at /home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:268:78\n    at arrayFilter (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/lodash/lodash.js:596:11)\n    at Function.filter (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/lodash/lodash.js:9241:14)\n    at SiteUtils.filterByHierarchy (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:268:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:121:25\n    at async Promise.all (index 0)\n    at async SiteUtils.filterByConfig (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/engine-server/lib/topics/site.js:120:47)\n    at async NextjsExportPod.plant (/home/paul/.nvm/versions/node/v19.0.0/lib/node_modules/@dendronhq/dendron-cli/node_modules/@dendronhq/pods-core/lib/builtin/NextjsExportPod.js:356:52)","type":"Error","msg":"Cannot read properties of undefined (reading 'custom')"}
unknown error [object Object]
```

## Dendron LOGS

``` json 
{"level":30,"time":1668047547099,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"Logger:configure","msg":"exit","logLevel":"info"}
{"level":30,"time":1668047547199,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"_activate","stage":"prod","isDebug":false,"logLevel":"info","logPath":"/home/paul/.config/VSCodium/logs/20221109T211339/window1/exthost/dendron.dendron","extensionPath":"/home/paul/.vscode-oss/extensions/dendron.dendron-0.117.0-universal","extensionUri":"/home/paul/.vscode-oss/extensions/dendron.dendron-0.117.0-universal","workspaceFolders":["/home/paul/Projects/Dendron/publish-ddaemon"]}
{"level":30,"time":1668047547217,"pid":251713,"hostname":"pop-os","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1668047547217,"pid":251713,"hostname":"pop-os","name":"SegmentClient","msg":"user telemetry setting: disabled by vscode config"}
{"level":30,"time":1668047547218,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"DendronExtension","msg":"initialized"}
{"level":30,"time":1668047547392,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"_activate","msg":"initializeWorkspace","wsType":"NATIVE","currentVersion":"0.117.0","previousGlobalVersion":"0.117.0","extensionInstallStatus":"NO_CHANGE"}
{"level":30,"time":1668047547553,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceActivator.init:postSetupTraits","wsRoot":"/home/paul/Projects/Dendron/publish-ddaemon"}
{"level":30,"time":1668047547578,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"runMigrationsIfNecessary","changes":[],"workspaceInstallStatus":"NO_CHANGE"}
{"level":30,"time":1668047547579,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceActivator.init:postMigration","wsRoot":"/home/paul/Projects/Dendron/publish-ddaemon"}
{"level":30,"time":1668047547601,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceActivator.init:postWsServiceInitialize","wsRoot":"/home/paul/Projects/Dendron/publish-ddaemon"}
{"level":30,"time":1668047547616,"pid":251713,"hostname":"pop-os","name":"execServer","state":"enter"}
{"level":30,"time":1668047547632,"pid":251713,"hostname":"pop-os","name":"execServer","state":"post:exec.node"}
{"level":30,"time":1668047549164,"pid":251764,"hostname":"pop-os","name":"SegmentClient","msg":"No cache path for Segment specified. Failed event uploads will not be retried."}
{"level":30,"time":1668047549165,"pid":251764,"hostname":"pop-os","name":"SegmentClient","msg":"user telemetry setting: disabled by vscode config"}
{"level":30,"time":1668047549179,"pid":251713,"hostname":"pop-os","name":"execServer","state":"message","message":"39533"}
{"level":30,"time":1668047549179,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"handleServerProcess","msg":"subprocess running","pid":251764}
{"level":30,"time":1668047549179,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"startServerProcess","msg":"post-start-server","port":39533,"durationStartServer":1570}
{"level":30,"time":1668047549180,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceActivator.init:verifyOrStartServerProcess","port":39533}
{"level":30,"time":1668047549190,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceActivator.init:exit"}
{"level":30,"time":1668047549201,"pid":251713,"hostname":"pop-os","name":"SegmentClient","msg":"user telemetry setting: disabled by vscode config"}
{"level":30,"time":1668047549201,"pid":251713,"hostname":"pop-os","name":"dendron","msg":"Telemetry is disabled? true"}
{"level":30,"time":1668047549201,"pid":251713,"hostname":"pop-os","name":"dendron","msg":"Segment Residual Cache Path is at /home/paul/.config/VSCodium/User/globalStorage/dendron.dendron/segmentresidualcache.log"}
{"level":30,"time":1668047549202,"pid":251713,"hostname":"pop-os","name":"SegmentClient","msg":"Attempting to flush residual segment data from file."}
{"level":30,"time":1668047549223,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"_activate:postSetupWorkspace","platform":"linux","extensions":[{"id":"dendron.dendron","version":"0.117.0","active":true},{"id":"dendron.dendron-paste-image","version":"1.1.0","active":false},{"id":"dendron.dendron-markdown-shortcuts"},{"id":"redhat.vscode-yaml","version":"1.10.1","active":true}],"vaults":[{"fsPath":"dependencies/gitlab.com/dentropy/dentropydaemon-wiki","remote":{"type":"git","url":"git@gitlab.com:dentropy/dentropydaemon-wiki.git"},"name":"dentropydaemon-wiki"}]}
{"level":30,"time":1668047549226,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"pre-execute"}
{"level":30,"time":1668047549227,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1668047549374,"pid":251764,"hostname":"pop-os","name":"logger","ctx":"parsingSchemas","fname":"root","root":{"fsPath":"dependencies/gitlab.com/dentropy/dentropydaemon-wiki","remote":{"type":"git","url":"git@gitlab.com:dentropy/dentropydaemon-wiki.git"},"name":"dentropydaemon-wiki"},"imports":[]}
{"level":30,"time":1668047550694,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"ReloadIndex.execute","durationEngineInit":1462}
{"level":30,"time":1668047550694,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1668047550694,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"dendron.reloadIndex:run","msg":"post-execute"}
{"level":30,"time":1668047550696,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1668047550696,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1668047550697,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1668047550697,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1668047550697,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"setupViews","msg":"init:treeViewV2"}
{"level":30,"time":1668047550698,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"setupBacklinkTreeView","msg":"init:backlinks"}
{"level":30,"time":1668047550733,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceActivator:activate","msg":"fin startClient","durationReloadWorkspace":1479}
{"level":30,"time":1668047550733,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"activateWorkspace","stage":"prod","msg":"enter"}
{"level":30,"time":1668047550742,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"togglePluginActiveContext","state":"togglePluginActiveContext: true"}
{"level":30,"time":1668047551023,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.117.0","previousExtensionVersion":"0.80.0"}
{"level":30,"time":1668047555684,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceWatcher:onWillSaveTextDocument","url":"/home/paul/Projects/Dendron/publish-ddaemon/dendron.yml","reason":"Manual","msg":"enter"}
{"level":30,"time":1668047566194,"pid":251713,"hostname":"pop-os","name":"dendron","msg":"sendSavedAnalytics"}
{"level":30,"time":1668047566196,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"AnalyticsUtils.sendSavedAnalytics","message":"start"}
{"level":40,"time":1668047566198,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"AnalyticsUtils.sendSavedAnalytics","msg":"failed to read the saved telemetry dir","telemetryDir":"/home/paul/.dendron/saved-telemetry"}
{"level":30,"time":1668047613305,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1668047613307,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047613372,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/paul/Projects/Dendron/publish-ddaemon/dendron.code-workspace"]}
{"level":30,"time":1668047613374,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047613376,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":"dendron.code-workspace"}
{"level":30,"time":1668047617539,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1668047617540,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047617571,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/paul/Projects/Dendron/publish-ddaemon/.gitignore"]}
{"level":30,"time":1668047617572,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047617573,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":".gitignore"}
{"level":30,"time":1668047628980,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1668047628982,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047629018,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/paul/Projects/Dendron/publish-ddaemon/.dendron.port.cli"]}
{"level":30,"time":1668047629018,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047629022,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":".dendron.port.cli"}
{"level":30,"time":1668047629766,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1668047629767,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047629789,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/paul/Projects/Dendron/publish-ddaemon/.dendron.ws"]}
{"level":30,"time":1668047629790,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047629791,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":".dendron.ws"}
{"level":30,"time":1668047637557,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":[]}
{"level":30,"time":1668047637558,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047637595,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WindowWatcher:onDidChangeVisibleTextEditors","editorPaths":["/home/paul/Projects/Dendron/publish-ddaemon/.gitignore"]}
{"level":30,"time":1668047637595,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"refreshBacklinksChangeActiveTextEditor"}
{"level":30,"time":1668047637598,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"WorkspaceWatcher:onFirstOpen","msg":"enter","fname":".gitignore"}
{"level":30,"time":1668048291096,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"pre-execute"}
{"level":30,"time":1668048291099,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1668048291109,"pid":251713,"hostname":"pop-os","name":"dendron","ctx":"dendron.dev.openLogs:run","msg":"post-execute"}
```

**Comment by dentropy** [comment]
I wrote a script so anyone can easily migrate to Obsidian

``` python3
from pathlib import Path
import glob
import os
import shutil

# Want to use Obsidian, run this script

dendron_path = os.getcwd() + "/MyDendronExistence/"
output_path  = dendron_path # os.getcwd() + "/export/"

dendron_markdown_files = glob.glob(dendron_path + "*.md")

def fix_file(file_path, out_path):
  file_name = file_path.split("/")[-1]
  final_file_name = "/" + file_name.split(".")[-2:-1][0] + ".md"
  new_path = "/".join(file_name.split(".")[0:-2])
  Path(out_path + new_path).mkdir(parents=True, exist_ok=True)
  Path(file_path).rename(out_path + new_path + final_file_name)
  # shutil.copyfile(file_path, out_path + new_path + final_file_name)

Path(output_path).mkdir(parents=True, exist_ok=True)
for file_name in dendron_markdown_files:
  fix_file(file_name, output_path)
```

**Comment by dentropy** [comment]
IDK if anyone will find this useful but I wrote a Dendron to Markdown folder script so I could start using Obsidian

``` sql
from pathlib import Path
import glob
import os
import shutil

# Want to use Obsidian, run this script

dendron_path = os.getcwd() + "/dentropydaemon-wiki/"
output_path  = dendron_path # os.getcwd() + "/export/"

dendron_markdown_files = glob.glob(dendron_path + "*.md")

def fix_file(file_path, out_path):
  file_name = file_path.split("/")[-1]
  final_file_name = "/" + file_name.split(".")[-2:-1][0] + ".md"
  new_path = "/".join(file_name.split(".")[0:-2])
  Path(out_path + new_path).mkdir(parents=True, exist_ok=True)
  Path(file_path).rename(out_path + new_path + final_file_name)
  # shutil.copyfile(file_path, out_path + new_path + final_file_name)

Path(output_path).mkdir(parents=True, exist_ok=True)
for file_name in dendron_markdown_files:
  fix_file(file_name, output_path)
```
