### ISSUE TITLE
Didn't work in fresh installed VSCode in Windows10 - v0.3.21

### ISSUE THREAD

**Issue by abtin** [dendronhq/dendron#38]
When I installed in Windows10 and tried to run Dendron: initialize workspace I got the following error:

Command 'Dendron: Initialize Workspace' resulted in an error (command 'dendron.initWS' not found)

`open '/tmp/dendron-dev.log'
	at Object.openSync (fs.js:447:3)
	at Object.func (electron/js2c/asar.js:140:31)
	at Object.func [as openSync] (electron/js2c/asar.js:140:31)
	at u (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:277:14975)
	at new c (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:277:15518)
	at Y (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:11:103292)
	at Function.J.destination (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:277:12746)
	at Object.t.createLogger (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:289:1838)
	at Object.<anonymous> (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:277:40786)
	at n (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:1:186)
	at Object.<anonymous> (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:277:37957)
	at n (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:1:186)
	at Object.<anonymous> (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:289:26096)
	at n (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:1:186)
	at Object.<anonymous> (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:11:92725)
	at n (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:1:186)
	at Object.<anonymous> (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:277:25295)
	at Object.<anonymous> (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:277:37699)
	at n (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:1:186)
	at Object.<anonymous> (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:277:70858)
	at n (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:1:186)
	at c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:1:985
	at Object.<anonymous> (c:\Users\me\.vscode\extensions\dendron.dendron-0.3.21\dist\extension.js:1:996)
	at Module.o._compile (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:15:956)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:937:10)
	at Module.load (internal/modules/cjs/loader.js:780:32)
	at Module._load (internal/modules/cjs/loader.js:693:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:974:348)
	at Function.i._load (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:943:839)
	at Function.n._load (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:940:198)
	at Module.require (internal/modules/cjs/loader.js:820:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:33:205)
	at h._loadCommonJSModule (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:945:34)
	at h._doActivateExtension (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:835:599)
	at h._activateExtension (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:834:692)
	at Object.actualActivateExtension (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:832:453)
	at h._activateExtension (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:405)
	at c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:83
	at Array.map (<anonymous>)
	at h._activateExtensions (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:71)
	at h._activateExtensions (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:601:140)
	at h.activateByEvent (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:598:546)
	at h._activateByEvent (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:833:300)
	at h._handleEagerExtensions (c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:838:218)
	at c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:841:872
	at processTicksAndRejections (internal/process/task_queues.js:85:5)`

**Comment by kevinslin** [comment]
this is related to #12. will be looking into windows installation this week. thanks for reporting!

**Comment by GalaticRailroad** [comment]
Can confirm I am having the same issue.

**Comment by abhijitnathwani** [comment]
I can confirm this still not working in v0.3.22 on Windows 10.

**Comment by alexisargyris** [comment]
Same here on v0.3.22, Win 10. Tried both with no folder open and having a folder open. Didn't make a difference.

**Comment by kevinslin** [comment]
writing to announce that windows support has landed in the latest version of dendron (0.3.29) 🎉🎉🎉

if you've installed a previous version of dendron, you can find upgrade instructions [here](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.upgrading.md)

you can find getting started instructions [here](https://github.com/dendronhq/dendron-template/blob/master/vault/pro.dendron.quickstart.md)

please let me know if you run into any issues, otherwise, happy note taking!

**Comment by GalaticRailroad** [comment]
Can confirm that I can now initialize workspace.  Thanks for the quick turnaround!

**Comment by alexisargyris** [comment]
Reporting success too! Also impressed by the smooth handling of initializing an already existing folder. Great job!

**Comment by kevinslin** [comment]
glad to hear its working for you and thanks for being part of the preview 🙏
if anything else comes up, feel free to submit another issue!

**Comment by abtin** [comment]
Thanks for the fix!
