### ISSUE TITLE
npm run build returns `TypeError: Cannot read properties of undefined (reading 'id')`

### ISSUE THREAD

**Issue by yviansu** [dendronhq/dendron#3813]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [x] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

I want to start a local server, however, when running `npx dendron publish build`, every thing is fine, but when I built HTML for my notes using `cd .next && npm run build`, an error occurs:
```
> Build error occurred
TypeError: Cannot read properties of undefined (reading 'id')
    at /home/syh/Documents/Dendron/Work/.next/.next/server/chunks/774.js:151:68
    at Array.filter (<anonymous>)
    at getNotePaths (/home/syh/Documents/Dendron/Work/.next/.next/server/chunks/774.js:151:38)
    at buildStaticPaths (/home/syh/Documents/Dendron/Work/.next/node_modules/next/dist/build/utils.js:497:37)
    at /home/syh/Documents/Dendron/Work/.next/node_modules/next/dist/build/utils.js:640:125
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/home/syh/Documents/Dendron/Work/.next/node_modules/next/dist/trace/trace.js:75:20) {
  type: 'TypeError'
}
```

## To Reproduce

I followed the (tutorial)[https://wiki.dendron.so/notes/svoot2ea4v5imu6rdrwuwmu/]
1. Run 'npx dendron publish build'
2. Run `cd .next && npm run build`
3. See error

## Expected behavior

I expect no error, and start a local server on localhost:3000 successfully.

## Screenshots

![image](https://user-images.githubusercontent.com/103162767/204177782-f60c53ca-b7cc-4008-9e34-badb4578975c.png)

## Desktop (please complete the following information)

- OS: Ubuntu 20.04.4 LTS && Windows 10
- Browser: chrome
- Versions:
  - Dendron Extension: 0.105.0

## Additional context

Nothing.

## Dendron Log file
[logs.txt](https://github.com/dendronhq/dendron/files/10099969/logs.txt)

**Comment by yviansu** [comment]
What's more, I have another question:
Can notes from a same dendron workspace be created both on the window platform and the linux platform?

I initialized a dendron workspace in my linux server, so I can create new notes in my linux desktop vscode. However, when I connect the server in windows through vscode ssh, I can't create new notes (`error while running command: Cannot read properties of undefined (reading 'map')` occurs).

I push the dendron workspace into a git repo, so I can both create new notes in my local linux and create new notes in my local windows, and do version control through git. Could this be the cause of the error `TypeError: Cannot read properties of undefined (reading 'id')`?

**Comment by hikchoi** [comment]
Hey @yviansu, looks like the version of `nextjs-template` is pretty old on your screenshot. Can you update `dendron-cli` to the latest version and try it out again?

**Comment by yviansu** [comment]
Hi @hikchoi 

I have updated `dendron-cli`, however, the same error occurs when I run the command `cd .next && npm run build`
![image](https://user-images.githubusercontent.com/103162767/204422432-9dbbb784-4896-4d25-8ff1-abfb5e282b28.png)

What's more, when I run the command `npm exec dendron publish dev`, the server can start on 0.0.0.0:3000, but when I reach the web, it will report error too.
![image](https://user-images.githubusercontent.com/103162767/204422625-be73e50b-f1c4-4a01-ade8-78d9de1d5146.png)

I think there is something wrong with `id`, could this be the cause?
> I push the dendron workspace into a git repo, so I can both create new notes in my local linux and create new notes in my local windows, and do version control through git. Could this be the cause of the error TypeError: Cannot read properties of undefined (reading 'id')?

**Comment by hikchoi** [comment]
@yviansu hey, thanks for the quick follow-up.

Could you also make sure that the dendron version (in VSCode) is up to date?

After that, remove the `.next` directory completely and try running a fresh `npx dendron publish init`.

Let me know how that goes

**Comment by yviansu** [comment]
@hikchoi Thanks for your reply.

My dendron version is v0.118.0, which is last updated in 11/23/2022.

I have removed the `.next` directory, and run `npx dendron publish init` as you suggested, a new `.next` directory is generated.
![image](https://user-images.githubusercontent.com/103162767/204468722-60b20454-5d3a-411e-9420-5636c5b1adf0.png)

However, when I run `npm exec dendron publish dev`, the same error occured.
![image](https://user-images.githubusercontent.com/103162767/204469174-197d359b-53d8-42b6-95b7-55a2c3af5af2.png)

When I run `cd .next && npm run build` after command `npx dendron publish build` , the same error occured too.
![image](https://user-images.githubusercontent.com/103162767/204469240-d910a4de-9d0a-41ee-a543-7d1f0fa8b846.png)

**Comment by hikchoi** [comment]
any particular reason you are using `npm exec` to run `dendron publish dev`?

Could you also share the content of `dendron.yml` if it doesn't contain any sensitive information?

**Comment by hikchoi** [comment]
tagging @namjul for visibility

**Comment by yviansu** [comment]
Hi, @hikchoi 

I followed the [publish quickstart note](https://wiki.dendron.so/notes/e5st4LFLtIwwbQmC6JBaF/) to publish my website.
I want to  launch a development server so that others can see my notes, so I choose the command `npx dendron publish dev`. 
(I might run command `npx exec dendron publish dev` before, but these two commands cause the same error `TypeError: Cannot read properties of undefined (reading 'id')`)

I have not seen logs related to `no note found`, however, when I launch my website `localhost:3000`, the log will show `wait  - compiling /_error (client and server)...`.
![image](https://user-images.githubusercontent.com/103162767/204478173-ac70d457-da71-4c38-b4c8-e3438a653a31.png)

My `dendron.yml` file is:
[dendron_yml.txt](https://github.com/dendronhq/dendron/files/10111160/dendron_yml.txt)
