### ISSUE TITLE
Using `hierarchy` in `dendron.yml` causes errors

### ISSUE THREAD

**Issue by KucharczykL** [dendronhq/dendron#3861]
## Please select the area your bug applies to. (Multiple selections are Possible. You can leave blank if you're not sure.)

- [ ] Workspace.  VSCode workspace, vaults, Intellisense/autocomplete, Dendron settings
- [ ] Lookup.  Dendron's Lookup Command
- [ ] Views.  Dendron Preview, Tree View, Side Panels in the UI
- [ ] Schema.  Dendron Schemas
- [ ] Pod.  Data import from / export to Dendron
- [X] Publish.  External Site Publish
- [ ] Markdown.  Markdown features, such as syntax support and features

## Describe the bug

Generating output with `yarn dendron publish export` on a vault that sets the `hierarchy` in `dendron.yml` causes an error.
Removing it fixes it.

## To Reproduce

1. Edit `dendron.yml` in this way:
```
siteHierarchies:
    - one
    - two
hierarchy:
    root:
        publishByDefault:
            vault1: false
            vault2: true
```
2. Generate the output with:
```
- "yarn add @dendronhq/dendron-cli@latest"
- "yarn dendron publish init"
- "yarn dendron publish export"
``` 
3. See error

## Expected behavior

Output is generated without error.

## Desktop (please complete the following information)

- OS: Alpine (the `node:current-alpine3.14` Docker image)
- Browser: N/A
- Versions (all that apply to bug):
  - Dendron Extension: N/A
  - VS Code version: N/A
  - Dendron CLI: 0.119.0

## Additional context

This is built in a container using Drone CI.

## Log File

```
+ yarn add @dendronhq/dendron-cli@latest
yarn add v1.22.18
[1/4] Resolving packages...
warning @dendronhq/dendron-cli > @dendronhq/engine-server > sqlite3 > node-gyp > make-fetch-happen > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 109 new dependencies.
info Direct dependencies
└─ @dendronhq/dendron-cli@0.119.0
info All dependencies
├─ @dendronhq/api-server@0.119.0
├─ @dendronhq/dendron-cli@0.119.0
├─ @dendronhq/dendron-viz@0.119.0
├─ @dendronhq/pods-core@0.119.0
├─ @dendronhq/remark-mermaid@0.4.0
├─ @gar/promisify@1.1.3
├─ @mapbox/node-pre-gyp@1.0.10
├─ @npmcli/fs@1.1.1
├─ @npmcli/move-file@1.1.2
├─ @sentry/core@7.11.1
├─ @swc/helpers@0.3.17
├─ @tootallnate/once@1.1.2
├─ agentkeepalive@4.2.1
├─ aggregate-error@3.1.0
├─ aproba@2.0.0
├─ are-we-there-yet@2.0.0
├─ async@3.2.4
├─ bcp-47-match@1.0.3
├─ cacache@15.3.0
├─ chownr@2.0.0
├─ clean-stack@2.2.0
├─ color-support@1.1.3
├─ console-control-strings@1.1.0
├─ d3-array@3.2.1
├─ d3-axis@3.0.0
├─ d3-brush@3.0.0
├─ d3-chord@3.0.1
├─ d3-contour@4.0.0
├─ d3-delaunay@6.0.2
├─ d3-dsv@3.0.1
├─ d3-ease@3.0.1
├─ d3-fetch@3.0.1
├─ d3-force@3.0.0
├─ d3-format@3.1.0
├─ d3-geo@3.0.1
├─ d3-hierarchy@3.1.2
├─ d3-interpolate@3.0.1
├─ d3-polygon@3.0.1
├─ d3-quadtree@3.0.1
├─ d3-random@3.0.1
├─ d3-scale-chromatic@3.0.0
├─ d3-scale@4.0.2
├─ d3-selection@3.0.0
├─ d3-shape@3.1.0
├─ d3-time-format@4.1.0
├─ d3-time@3.1.0
├─ d3-transition@3.0.1
├─ d3-zoom@3.0.0
├─ d3@7.7.0
├─ delaunator@5.0.0
├─ delegates@1.0.0
├─ detect-libc@2.0.1
├─ direction@1.0.4
├─ encoding@0.1.13
├─ env-paths@2.2.1
├─ err-code@2.0.3
├─ escalade@3.1.1
├─ fs-minipass@2.1.0
├─ gauge@3.0.2
├─ handlebars@4.7.7
├─ has-unicode@2.0.1
├─ hast-util-select@4.0.2
├─ http-proxy-agent@4.0.1
├─ humanize-ms@1.2.1
├─ imurmurhash@0.1.4
├─ indent-string@4.0.0
├─ infer-owner@1.0.4
├─ internmap@2.0.3
├─ ip@2.0.0
├─ is-lambda@1.0.1
├─ make-dir@3.1.0
├─ make-fetch-happen@9.1.0
├─ micromatch@4.0.5
├─ minimist@1.2.7
├─ minipass-fetch@1.4.1
├─ minipass-pipeline@1.2.4
├─ minipass-sized@1.0.3
├─ minizlib@2.1.2
├─ mkdirp@1.0.4
├─ neo-async@2.6.2
├─ neverthrow@5.1.0
├─ node-addon-api@4.3.0
├─ node-gyp@8.4.1
├─ nopt@5.0.0
├─ npmlog@5.0.1
├─ p-map@4.0.0
├─ promise-inflight@1.0.1
├─ promise-retry@2.0.1
├─ react-dom@17.0.2
├─ react@17.0.2
├─ retry@0.12.0
├─ robust-predicates@3.0.1
├─ rw@1.3.3
├─ scheduler@0.20.2
├─ smart-buffer@4.2.0
├─ socks-proxy-agent@6.2.1
├─ socks@2.7.1
├─ source-map@0.6.1
├─ sqlite3@5.1.3
├─ ssri@8.0.1
├─ tar@6.1.13
├─ textextensions@5.15.0
├─ uglify-js@3.17.4
├─ unique-filename@1.1.1
├─ unique-slug@2.0.2
├─ wide-align@1.1.5
├─ wordwrap@1.0.0
├─ zod-validation-error@0.1.1
└─ zod@3.19.1
Done in 28.53s.
+ apk add git
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20220614-r0)
(2/7) Installing brotli-libs (1.0.9-r5)
(3/7) Installing nghttp2-libs (1.43.0-r0)
(4/7) Installing libcurl (7.79.1-r3)
(5/7) Installing expat (2.5.0-r0)
(6/7) Installing pcre2 (10.36-r1)
(7/7) Installing git (2.32.4-r0)
Executing busybox-1.33.1-r7.trigger
Executing ca-certificates-20220614-r0.trigger
OK: 21 MiB in 23 packages
+ yarn dendron publish init
yarn run v1.22.18
$ /drone/src/node_modules/.bin/dendron publish init

===================
Telemetry notice 🌱
===================
Dendron collects limited usage data to help improve the quality of our software.

You can learn everything about our telemetry policies by visiting the following link: 
https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html

If you would like to opt out, follow the instructions below: 
https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html#how-to-opt-out-of-data-collection
🌱 checking if .next directory exists.
🌱 .next directory does not exist
🌱 Initializing NextJS template.
- Cloning NextJS template...
🌱 Successfully cloned.
- Cloning NextJS template...
- Installing dependencies... This may take a while.
🌱 All dependencies installed.
- Installing dependencies... This may take a while.
Done in 57.70s.
+ yarn dendron publish export
yarn run v1.22.18
$ /drone/src/node_modules/.bin/dendron publish export
🌱 checking if NextJS template is initialized
🌱 NextJS template is already initialized.
generating metadata for publishing...

> @dendronhq/nextjs-template@0.116.3 export
> npm run build && next export


> @dendronhq/nextjs-template@0.116.3 build
> npm run copy:robotstxt && next build


> @dendronhq/nextjs-template@0.116.3 copy:robotstxt
> npx cpx assets/robots.txt public/

info  - Loaded env from /drone/src/.next/.env.production
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

info  - Linting and checking validity of types...
info  - Creating an optimized production build...
info  - Compiled successfully
info  - Collecting page data...
{"level":50,"time":1670849104529,"pid":136,"hostname":"1cd6c15ee88b","name":"publish <cmd>","shortMessage":"Command failed with exit code 1: npm run export","command":"npm run export","exitCode":1,"stdout":"\n> @dendronhq/nextjs-template@0.116.3 export\n> npm run build && next export\n\n\n> @dendronhq/nextjs-template@0.116.3 build\n> npm run copy:robotstxt && next build\n\n\n> @dendronhq/nextjs-template@0.116.3 copy:robotstxt\n> npx cpx assets/robots.txt public/\n\ninfo  - Loaded env from /drone/src/.next/.env.production\nwarn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache\nAttention: Next.js now collects completely anonymous telemetry regarding usage.\nThis information is used to shape Next.js' roadmap and prioritize features.\nYou can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:\nhttps://nextjs.org/telemetry\n\ninfo  - Linting and checking validity of types...\ninfo  - Creating an optimized production build...\ninfo  - Compiled successfully\ninfo  - Collecting page data...","stderr":"TypeError: Cannot read properties of undefined (reading 'id')\n    at /drone/src/.next/.next/server/chunks/128.js:88:68\n    at Array.filter (<anonymous>)\n    at getNotePaths (/drone/src/.next/.next/server/chunks/128.js:88:38)\n    at buildStaticPaths (/drone/src/.next/node_modules/next/dist/build/utils.js:592:39)\n    at /drone/src/.next/node_modules/next/dist/build/utils.js:886:121\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Span.traceAsyncFn (/drone/src/.next/node_modules/next/dist/trace/trace.js:79:20)\n\n> Build error occurred\nError: Failed to collect page data for /notes/[id]\n    at /drone/src/.next/node_modules/next/dist/build/utils.js:916:15\n    at processTicksAndRejections (node:internal/process/task_queues:96:5) {\n  type: 'Error'\n}","failed":true,"timedOut":false,"isCanceled":false,"killed":false,"stack":"Error: Command failed with exit code 1: npm run export\nTypeError: Cannot read properties of undefined (reading 'id')\n    at /drone/src/.next/.next/server/chunks/128.js:88:68\n    at Array.filter (<anonymous>)\n    at getNotePaths (/drone/src/.next/.next/server/chunks/128.js:88:38)\n    at buildStaticPaths (/drone/src/.next/node_modules/next/dist/build/utils.js:592:39)\n    at /drone/src/.next/node_modules/next/dist/build/utils.js:886:121\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Span.traceAsyncFn (/drone/src/.next/node_modules/next/dist/trace/trace.js:79:20)\n\n> Build error occurred\nError: Failed to collect page data for /notes/[id]\n    at /drone/src/.next/node_modules/next/dist/build/utils.js:916:15\n    at processTicksAndRejections (node:internal/process/task_queues:96:5) {\n  type: 'Error'\n}\n\n> @dendronhq/nextjs-template@0.116.3 export\n> npm run build && next export\n\n\n> @dendronhq/nextjs-template@0.116.3 build\n> npm run copy:robotstxt && next build\n\n\n> @dendronhq/nextjs-template@0.116.3 copy:robotstxt\n> npx cpx assets/robots.txt public/\n\ninfo  - Loaded env from /drone/src/.next/.env.production\nwarn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache\nAttention: Next.js now collects completely anonymous telemetry regarding usage.\nThis information is used to shape Next.js' roadmap and prioritize features.\nYou can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:\nhttps://nextjs.org/telemetry\n\ninfo  - Linting and checking validity of types...\ninfo  - Creating an optimized production build...\ninfo  - Compiled successfully\ninfo  - Collecting page data...\n    at makeError (/drone/src/node_modules/@dendronhq/engine-server/node_modules/execa/lib/error.js:59:11)\n    at handlePromise (/drone/src/node_modules/@dendronhq/engine-server/node_modules/execa/index.js:114:26)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PublishCLICommand.export (/drone/src/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:408:9)\n    at async PublishCLICommand.execute (/drone/src/node_modules/@dendronhq/dendron-cli/lib/src/commands/publishCLICommand.js:171:21)\n    at async Object.CLICommand.eval [as handler] (/drone/src/node_modules/@dendronhq/dendron-cli/lib/src/commands/base.js:58:25)","type":"Error","msg":"Command failed with exit code 1: npm run export\nTypeError: Cannot read properties of undefined (reading 'id')\n    at /drone/src/.next/.next/server/chunks/128.js:88:68\n    at Array.filter (<anonymous>)\n    at getNotePaths (/drone/src/.next/.next/server/chunks/128.js:88:38)\n    at buildStaticPaths (/drone/src/.next/node_modules/next/dist/build/utils.js:592:39)\n    at /drone/src/.next/node_modules/next/dist/build/utils.js:886:121\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Span.traceAsyncFn (/drone/src/.next/node_modules/next/dist/trace/trace.js:79:20)\n\n> Build error occurred\nError: Failed to collect page data for /notes/[id]\n    at /drone/src/.next/node_modules/next/dist/build/utils.js:916:15\n    at processTicksAndRejections (node:internal/process/task_queues:96:5) {\n  type: 'Error'\n}\n\n> @dendronhq/nextjs-template@0.116.3 export\n> npm run build && next export\n\n\n> @dendronhq/nextjs-template@0.116.3 build\n> npm run copy:robotstxt && next build\n\n\n> @dendronhq/nextjs-template@0.116.3 copy:robotstxt\n> npx cpx assets/robots.txt public/\n\ninfo  - Loaded env from /drone/src/.next/.env.production\nwarn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache\nAttention: Next.js now collects completely anonymous telemetry regarding usage.\nThis information is used to shape Next.js' roadmap and prioritize features.\nYou can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:\nhttps://nextjs.org/telemetry\n\ninfo  - Linting and checking validity of types...\ninfo  - Creating an optimized production build...\ninfo  - Compiled successfully\ninfo  - Collecting page data..."}
unknown error [object Object]
Done in 60.37s.

```

**Comment by hikchoi** [comment]
Thank for the report.

pinging @namjul for visibility
