### ISSUE TITLE
EleventyConfig Error while trying to publish to localhost

### ISSUE THREAD

**Issue by misra-suyash** [dendronhq/dendron#431]
I am following the directions listed here to view my site at localhost:8080
https://dendron.so/notes/861e4e48-dcc5-4813-a695-8940ba6e64d3.html

However I get the following error. Is there something missing in the documentation? 

{ EleventyConfigError: Error in your Eleventy config file '/Users/smisra/dendron-template/vault/node_modules/@dendronhq/dendron-11ty/.eleventy.js'.
    at TemplateConfig.mergeConfig (/Users/smisra/dendron-template/vault/node_modules/@11ty/eleventy/src/TemplateConfig.js:104:15)
    at TemplateConfig.setProjectConfigPath (/Users/smisra/dendron-template/vault/node_modules/@11ty/eleventy/src/TemplateConfig.js:53:24)
    at Eleventy.setConfigPathOverride (/Users/smisra/dendron-template/vault/node_modules/@11ty/eleventy/src/Eleventy.js:189:14)
    at compile (/Users/smisra/dendron-template/vault/node_modules/@dendronhq/dendron-11ty/index.js:21:8)
    at BuildSiteCommandV2.execute (/Users/smisra/dendron-template/vault/node_modules/@dendronhq/dendron-cli/lib/src/commands/build-site-v2.js:84:15)
    at opts.engine.init.then (/Users/smisra/dendron-template/vault/node_modules/@dendronhq/dendron-cli/lib/src/commands/soil.js:92:29)
  name: 'EleventyConfigError',
  originalError:
   /Users/smisra/dendron-template/vault/node_modules/@dendronhq/dendron-11ty/libs/utils.js:65
     static getUrl = (note) => {
                   ^
   
   SyntaxError: Unexpected token =
       at new Script (vm.js:80:7)
       at createScript (vm.js:274:10)
       at Object.runInThisContext (vm.js:326:10)
       at Module._compile (internal/modules/cjs/loader.js:664:28)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
       at Module.load (internal/modules/cjs/loader.js:600:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
       at Function.Module._load (internal/modules/cjs/loader.js:531:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at require (internal/modules/cjs/helpers.js:22:18)
       at Object.<anonymous> (/Users/smisra/dendron-template/vault/node_modules/@dendronhq/dendron-11ty/libs/shortcodes.js:13:5)
       at Module._compile (internal/modules/cjs/loader.js:701:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
       at Module.load (internal/modules/cjs/loader.js:600:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
       at Function.Module._load (internal/modules/cjs/loader.js:531:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at require (internal/modules/cjs/helpers.js:22:18)
       at Object.<anonymous> (/Users/smisra/dendron-template/vault/node_modules/@dendronhq/dendron-11ty/.eleventy.js:3:20)
       at Module._compile (internal/modules/cjs/loader.js:701:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
       at Module.load (internal/modules/cjs/loader.js:600:32) }
Waiting for the debugger to disconnect...

**Comment by kevins8** [comment]
That looks like an old version of node. Can you make sure you are using
node version v12 or above?

**Comment by misra-suyash** [comment]
Ahh yes. Missed that. Thanks for the feedback and also appreciate the work you guys are doing!
