### ISSUE TITLE
dendron-cli doctor throws error

### ISSUE THREAD

**Issue by Bassmann** [dendronhq/dendron#492]
**Describe the bug**
I try to run `npx dendron-cli doctor --wsRoot . --actions "h1ToTitle"` which throws the error 

```
TypeError: doctorAction is not a function
    at C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:148:20
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
    at async C:\Users\Bassmann\Documents\Archiv\Dendron\node_modules\@dendronhq\dendron-cli\lib\src\commands\doctor.js:143:13
```
**To Reproduce**
1. Open command prompt
2. Run the dendron-cli doctor command

**Expected behavior**
Update my notes to fit to Dendron

**Desktop (please complete the following information):**
 - OS: windows 10
 - Dendron 0.29
 - Dendorn cli Version 0.29.2-alpha.0

**Dendron Log file**
Please attach the output of `>Dev:Dendron: Open Logs` here

**Comment by kevinslin** [comment]
should be fixed in the latest version of early seed release. if you try it now with `--action` instead of `--actions`, the command will work

**Comment by Bassmann** [comment]
It's indeed fixed, thanks a lot! You may want to fix the usage text since it still mentions `..actions`
