### ISSUE TITLE
Mandated Lowercase?

### ISSUE THREAD

**Issue by PhilipWhiteside** [dendronhq/dendron#516]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [x] Hierarchy
- [ ] Graph
- [ ] Misc (Choose this if your not sure)

## To Reproduce

When trying to open files it's searching for lowercase, despite having been made with capital letters. I did not see a mandate for lowercase, just recommendation. If this is the case, please let me know and I'll update my files to match. The only change I see is that Dendron has been updated. Nothing in the release notes say mandated lowercase https://dendron.so/notes/1dad9378-8fcf-4859-bede-cc44279ba12d.html

1. Ctrl+L to open Dendron bar
2. Search for note
3. Open note

## Expected behavior

Open the file.

## Screenshots

![Screenshot from 2021-03-02 15-07-48 185130312](https://user-images.githubusercontent.com/22427598/109668437-1809a580-7b69-11eb-9171-0850da675fb3.png)
![Screenshot from 2021-03-02 15-07-44 781183888](https://user-images.githubusercontent.com/22427598/109668443-193ad280-7b69-11eb-8b6b-5f422486aa29.png)
![Screenshot from 2021-03-02 15-10-04 497248905](https://user-images.githubusercontent.com/22427598/109668833-70d93e00-7b69-11eb-825d-5c3eb0c73a9f.png)
![Screenshot from 2021-03-02 15-09-49 478707950](https://user-images.githubusercontent.com/22427598/109668835-7171d480-7b69-11eb-8176-c4e7a502ce8c.png)

## Desktop (please complete the following information)

- OS: Fedora 33
- Browser: VSCodium 1.53.2, Electron 11.2.1, Chrome 87.0.4280.141, Node.js 12.18.3, V8 8.7.220.31-electron.0, OS Linux x64 5.10.19-200.fc33.x86_53
- Version: 0.31.0

## Additional context

NA

## Dendron Log file

```
{"level":30,"time":1614697403519,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"Logger:configure","msg":"exit","log_level":"info"}
{"level":30,"time":1614697403554,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"_activate","stage":"dev","isDebug":false,"logPath":"/home/pwhitesi/.var/app/com.vscodium.codium/config/VSCodium/logs/20210302T150320/exthost1/dendron.dendron","logLevel":"info","extensionPath":"/home/pwhitesi/.var/app/com.vscodium.codium/data/codium/extensions/dendron.dendron-0.31.0","extensionUri":{"$mid":1,"fsPath":"/home/pwhitesi/.var/app/com.vscodium.codium/data/codium/extensions/dendron.dendron-0.31.0","path":"/home/pwhitesi/.var/app/com.vscodium.codium/data/codium/extensions/dendron.dendron-0.31.0","scheme":"file"},"storagePath":"/home/pwhitesi/.var/app/com.vscodium.codium/config/VSCodium/User/workspaceStorage/31064ccdb91541926dfa49d750726cfd/dendron.dendron","workspaceFile":{"$mid":1,"fsPath":"/home/pwhitesi/Documents/Notebook/dendron.code-workspace","external":"file:///home/pwhitesi/Documents/Notebook/dendron.code-workspace","path":"/home/pwhitesi/Documents/Notebook/dendron.code-workspace","scheme":"file"},"workspaceFolders":[{"uri":{"$mid":1,"fsPath":"/home/pwhitesi/Documents/Notebook/Notes","external":"file:///home/pwhitesi/Documents/Notebook/Notes","path":"/home/pwhitesi/Documents/Notebook/Notes","scheme":"file"},"name":"Notes","index":0},{"uri":{"$mid":1,"fsPath":"/home/pwhitesi/Documents/Notebook/Confidential","external":"file:///home/pwhitesi/Documents/Notebook/Confidential","path":"/home/pwhitesi/Documents/Notebook/Confidential","scheme":"file"},"name":"Confidential","index":1},{"uri":{"$mid":1,"fsPath":"/home/pwhitesi/Documents/Notebook/vault2","external":"file:///home/pwhitesi/Documents/Notebook/vault2","path":"/home/pwhitesi/Documents/Notebook/vault2","scheme":"file"},"name":"vault2","index":2}]}
{"level":30,"time":1614697403555,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"DendronWorkspace","msg":"initialized"}
{"level":30,"time":1614697403646,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"_activate","config":{"version":1,"vaults":[{"fsPath":"Notes"},{"fsPath":"Confidential","visibility":"private"},{"fsPath":"vault2"}],"lookupConfirmVaultOnCreate":true},"configMigrated":false,"msg":"read dendron config"}
{"level":30,"time":1614697403674,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"_activate","wsConfig":{"folders":[{"path":"Notes"},{"path":"Confidential"},{"path":"vault2"}],"settings":{"dendron.rootDir":".","files.autoSave":"onFocusChange","pasteImage.path":"${currentFileDir}/assets/images","pasteImage.prefix":"/","markdown-preview-enhanced.enableWikiLinkSyntax":true,"markdown-preview-enhanced.wikiLinkFileExtension":".md","editor.snippetSuggestions":"inline","editor.suggest.snippetsPreventQuickSuggestions":false,"editor.suggest.showSnippets":true,"editor.tabCompletion":"on","spellright.language":[],"spellright.documentTypes":["latex"]},"extensions":{"recommendations":["dendron.dendron-paste-image","equinusocio.vsc-material-theme","dendron.dendron-markdown-shortcuts","dendron.dendron-markdown-preview-enhanced","dendron.dendron-markdown-links","github.github-vscode-theme"],"unwantedRecommendations":["dendron.dendron-markdown-notes","shd101wyy.markdown-preview-enhanced","kortina.vscode-markdown-notes","mushan.vscode-paste-image"]}},"wsConfigMigrated":{},"msg":"read wsConfig"}
{"level":30,"time":1614697403680,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"_activate","installedGlobalVersion":"0.31.0","migratedGlobalVersion":"0.31.0","previousGlobalVersion":"0.30.0","previousWsVersion":"0.31.0","platform":"linux","extensions":[{"id":"dendron.dendron-paste-image","version":"1.0.4","active":false},{"id":"equinusocio.vsc-material-theme"},{"id":"dendron.dendron-markdown-shortcuts","version":"0.12.1","active":true},{"id":"dendron.dendron-markdown-preview-enhanced","version":"0.10.28","active":false},{"id":"dendron.dendron-markdown-links","version":"0.6.19","active":false},{"id":"github.github-vscode-theme","version":"3.0.0","active":false}],"vaults":[{"fsPath":"Notes"},{"fsPath":"Confidential","visibility":"private"},{"fsPath":"vault2"}]}
{"level":30,"time":1614697403681,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"startServer","logLevel":"info"}
{"level":30,"time":1614697403685,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"_activate","msg":"post-start-server","port":38791}
{"level":30,"time":1614697403687,"pid":98,"hostname":"x1carbon","name":"logger","ctx":"FileStorageV2","wsRoot":"/home/pwhitesi/Documents/Notebook","vaultsv3":[{"fsPath":"Notes"},{"fsPath":"Confidential","visibility":"private"},{"fsPath":"vault2"}],"level":"info"}
{"level":30,"time":1614697403687,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"ReloadIndex.execute","msg":"enter"}
{"level":30,"time":1614697405180,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"ReloadIndex.execute","msg":"exit"}
{"level":30,"time":1614697405180,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"reloadWorkspace","msg":"post-ws.reloadWorkspace"}
{"level":30,"time":1614697405181,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"reloadWorkspace","msg":"exit"}
{"level":30,"time":1614697405183,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"postReloadWorkspace","msg":"same wsVersion"}
{"level":30,"time":1614697405183,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"postReloadWorkspace","msg":"exit"}
{"level":30,"time":1614697405185,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1614697405225,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"setupViews","msg":"init:backlinks"}
{"level":30,"time":1614697405226,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"activateWorkspace","stage":"dev","msg":"enter"}
{"level":30,"time":1614697405234,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"toggleViews","msg":"views enabled: true"}
{"level":30,"time":1614697405234,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"_activate","msg":"fin startClient"}
{"level":30,"time":1614697405234,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"showWelcomeOrWhatsNew","version":"0.31.0","previousVersion":"0.31.0"}
{"level":30,"time":1614697405235,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"showWelcomeOrWhatsNew","msg":"not first time install"}
{"level":30,"time":1614697405974,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"TreeView:getChildren","msg":"reconstructing tree"}
{"level":30,"time":1614697410276,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"l:run","msg":"pre-execute"}
{"level":30,"time":1614697410276,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupCommand:execute","opts":{"flavor":"note"},"msg":"enter"}
{"level":30,"time":1614697410277,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupCommand:execute","profile":0,"msg":"postCreateController"}
{"level":30,"time":1614697410277,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupCommand:execute","profile":1,"msg":"post:extractRange"}
{"level":30,"time":1614697410277,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","msg":"enter","cleanOpts":{"ignoreFocusOut":true}}
{"level":30,"time":1614697410280,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"post:createQuickPick"}
{"level":30,"time":1614697410280,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"post:createProvider"}
{"level":30,"time":1614697410281,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerBehavior","activeButtons":[{"iconPathNormal":{"id":"find-selection"},"iconPathPressed":{"id":"menu-selection"},"type":"selectionExtract","pressed":true,"title":"Selection Extract","canToggle":true,"opts":{"title":"Selection Extract","iconOff":"find-selection","iconOn":"menu-selection","type":"selectionExtract"}}]}
{"level":30,"time":1614697410281,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupCommand:execute","profile":5,"msg":"post:show"}
{"level":30,"time":1614697410283,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"root","source":"updatePickerBehavior:normal"}
{"level":30,"time":1614697410292,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"root","source":"updatePickerBehavior:normal","profile":9,"cancelled":false}
{"level":30,"time":1614697410292,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"post:updatePickerBehavior"}
{"level":30,"time":1614697410292,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"post:provide"}
{"level":30,"time":1614697410293,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":2,"msg":"exit"}
{"level":30,"time":1614697410293,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"l:run","msg":"post-execute"}
{"level":30,"time":1614697411424,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"t","source":"onValueChange"}
{"level":30,"time":1614697411425,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1614697411429,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1614697411433,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":8}
{"level":30,"time":1614697411433,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"t","source":"onValueChange","profile":9,"cancelled":false}
{"level":30,"time":1614697411612,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"te","source":"onValueChange"}
{"level":30,"time":1614697411612,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1614697411619,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1614697411651,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":38}
{"level":30,"time":1614697411651,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"te","source":"onValueChange","profile":38,"cancelled":false}
{"level":30,"time":1614697411763,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"ter","source":"onValueChange"}
{"level":30,"time":1614697411763,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1614697411771,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1614697411810,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":46}
{"level":30,"time":1614697411810,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"ter","source":"onValueChange","profile":47,"cancelled":false}
{"level":30,"time":1614697411915,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"terr","source":"onValueChange"}
{"level":30,"time":1614697411915,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1614697411917,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1614697411939,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":23}
{"level":30,"time":1614697411940,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"terr","source":"onValueChange","profile":24,"cancelled":false}
{"level":30,"time":1614697412056,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"terra","source":"onValueChange"}
{"level":30,"time":1614697412056,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1614697412058,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1614697412083,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":27}
{"level":30,"time":1614697412084,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"terra","source":"onValueChange","profile":27,"cancelled":false}
{"level":30,"time":1614697413394,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"onDidAcceptSingle","msg":"enter","value":"terra","opts":{"flavor":"note"},"noteOverrides":{},"selectedItems":[{"fname":"tech.terraform.provider.build","id":"ee43fd6f-bde3-41e1-a1da-11b18db0ae8e","children":[],"vault":{"fsPath":"Notes"},"parent":"89756aa0-c720-446e-a5db-8300f2e87115"}],"activeItems":[{"fname":"tech.terraform.provider.build","id":"ee43fd6f-bde3-41e1-a1da-11b18db0ae8e","children":[],"vault":{"fsPath":"Notes"},"parent":"89756aa0-c720-446e-a5db-8300f2e87115"}]}
{"level":50,"time":1614697413400,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"showDocAndHidePicker","err":{"type":"Error","message":"cannot open file:///home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md. Detail: Unable to read file '/home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md' (Error: Unable to resolve non-existing file '/home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md')","stack":"Error: cannot open file:///home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md. Detail: Unable to read file '/home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md' (Error: Unable to resolve non-existing file '/home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md')\n    at file:///app/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:109144","name":"Error"},"msg":"exit"}
{"level":50,"time":1614697413402,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupProvider:onAccept","err":{"type":"r","message":"","stack":"Error: \n\tat /home/pwhitesi/.var/app/com.vscodium.codium/data/codium/extensions/dendron.dendron-0.31.0/dist/extension.js:466:955075\n\tat processTicksAndRejections (internal/process/task_queues.js:97:5)","status":"unknown","msg":"","friendly":"something went wrong. please submit a bug report to https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title= with the output of `Dendron: Open Log`","payload":"{\"msg\":\"cannot open file:///home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md. Detail: Unable to read file '/home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md' (Error: Unable to resolve non-existing file '/home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md')\",\"stack\":\"Error: cannot open file:///home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md. Detail: Unable to read file '/home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md' (Error: Unable to resolve non-existing file '/home/pwhitesi/Documents/Notebook/Notes/tech.terraform.provider.build.md')\\n    at file:///app/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:109144\"}"}}
{"level":30,"time":1614697422677,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"l:run","msg":"pre-execute"}
{"level":30,"time":1614697422677,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupCommand:execute","opts":{"flavor":"note"},"msg":"enter"}
{"level":30,"time":1614697422678,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupCommand:execute","profile":0,"msg":"postCreateController"}
{"level":30,"time":1614697422678,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupCommand:execute","profile":0,"msg":"post:extractRange"}
{"level":30,"time":1614697422678,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","msg":"enter","cleanOpts":{"ignoreFocusOut":true}}
{"level":30,"time":1614697422678,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":0,"msg":"post:createQuickPick"}
{"level":30,"time":1614697422678,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":0,"msg":"post:createProvider"}
{"level":30,"time":1614697422678,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerBehavior","activeButtons":[{"iconPathNormal":{"id":"find-selection"},"iconPathPressed":{"id":"menu-selection"},"type":"selectionExtract","pressed":true,"title":"Selection Extract","canToggle":true,"opts":{"title":"Selection Extract","iconOff":"find-selection","iconOn":"menu-selection","type":"selectionExtract"}}]}
{"level":30,"time":1614697422679,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupCommand:execute","profile":1,"msg":"post:show"}
{"level":30,"time":1614697422679,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"root","source":"updatePickerBehavior:normal"}
{"level":30,"time":1614697422691,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"root","source":"updatePickerBehavior:normal","profile":12,"cancelled":false}
{"level":30,"time":1614697422691,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":0,"msg":"post:updatePickerBehavior"}
{"level":30,"time":1614697422691,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":0,"msg":"post:provide"}
{"level":30,"time":1614697422692,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"LookupControllerV2:show","profile":0,"msg":"exit"}
{"level":30,"time":1614697422692,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"l:run","msg":"post-execute"}
{"level":30,"time":1614697423015,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"d","source":"onValueChange"}
{"level":30,"time":1614697423015,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1614697423016,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1614697423018,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":2}
{"level":30,"time":1614697423018,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"d","source":"onValueChange","profile":3,"cancelled":false}
{"level":30,"time":1614697426449,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"l:run","msg":"pre-execute"}
{"level":30,"time":1614697426449,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"execute","opts":{}}
{"level":30,"time":1614697426461,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"l:run","msg":"post-execute"}
{"level":30,"time":1614697426602,"pid":98,"hostname":"x1carbon","name":"dendron","ctx":"WindowWatcher:onDidChangeActiveTextEditor","msg":"enter","uri":{"$mid":1,"fsPath":"/home/pwhitesi/.var/app/com.vscodium.codium/config/VSCodium/logs/20210302T150320/exthost1/dendron.dendron/dendron.log","external":"file:///home/pwhitesi/.var/app/com.vscodium.codium/config/VSCodium/logs/20210302T150320/exthost1/dendron.dendron/dendron.log","path":"/home/pwhitesi/.var/app/com.vscodium.codium/config/VSCodium/logs/20210302T150320/exthost1/dendron.dendron/dendron.log","scheme":"file"}}
```

**Comment by kevinslin** [comment]
You're right - this is a regression for fixing a mixed casing bug. Just pushed a fix and published as 0.31.1

**Comment by PhilipWhiteside** [comment]
It works on 0.31.1, thank you very much for the quick fix and push!

**Comment by kevinslin** [comment]
No problem and thanks for catching this!
