### ISSUE TITLE
Lookup hangs on non-dendron workspace

### ISSUE THREAD

**Issue by vivkr** [dendronhq/dendron#586]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] UI
- [ ] Workbench
- [ ] Publishing
- [ ] Pods
- [ ] Markdown
- [ ] Hierarchy
- [ ] Graph
- [X] Misc (Choose this if your not sure)

## Describe the bug

Using cmd+shift+down in a non-dendron workspace causes lookup to open and then lookup hangs.

## To Reproduce

1. Open a non-dendron workspace with the Dendron extension enables.
2. Open any file and press cmd+shift+down.

## Expected behavior

Expected that lookup is not called in a non-dendron workspace. Fixed it by disabling the Dendron extension for the workspace, and looks like I have to do this for all workspaces.

## Screenshots

<img width="768" alt="Screenshot 2021-03-28 at 18 16 46" src="https://user-images.githubusercontent.com/41533822/112755449-caf6e300-8ff1-11eb-98c4-120947745ad4.png">
This is what lookup looks like when it hangs

## Desktop (please complete the following information)

- OS: macOS
- Dendron: 0.34

## Dendron Log file

```
info: {"ctx":"Logger:configure","msg":"exit","log_level":"info"}
info: {"ctx":"_activate","stage":"dev","isDebug":false,"logPath":"/Users/vivek/Library/Application Support/Code/logs/20210328T181543/exthost4/dendron.dendron","logLevel":"info","extensionPath":"/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0","extensionUri":{"$mid":1,"fsPath":"/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0","path":"/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0","scheme":"file"}}
info: {"ctx":"DendronWorkspace","msg":"initialized"}
info: {"ctx":"dendron not active"}
info: {"ctx":"toggleViews","msg":"views enabled: false"}
info: {"ctx":"u:run","msg":"pre-execute"}
info: {"ctx":"LookupCommand:execute","opts":{"flavor":"note","value":"Untitled-1."},"msg":"enter"}
info: {"ctx":"LookupCommand:execute","profile":0,"msg":"postCreateController"}
info: {"ctx":"LookupCommand:execute","profile":1,"msg":"post:extractRange"}
info: {"ctx":"LookupControllerV2:show","msg":"enter","cleanOpts":{"value":"Untitled-1.","ignoreFocusOut":true}}
info: {"ctx":"LookupControllerV2:show","profile":0,"msg":"post:createQuickPick"}
info: {"ctx":"LookupControllerV2:show","profile":0,"msg":"post:createProvider"}
info: {"ctx":"updatePickerBehavior","activeButtons":[{"iconPathNormal":{"id":"find-selection"},"iconPathPressed":{"id":"menu-selection"},"type":"selectionExtract","pressed":true,"title":"Selection Extract","canToggle":true,"opts":{"title":"Selection Extract","iconOff":"find-selection","iconOn":"menu-selection","type":"selectionExtract"}}]}
info: {"ctx":"LookupCommand:execute","profile":2,"msg":"post:show"}
info: {"ctx":"LookupControllerV2:show","profile":0,"msg":"post:updatePickerBehavior"}
info: {"ctx":"LookupControllerV2:show","profile":0,"msg":"post:provide"}
info: {"ctx":"LookupControllerV2:show","profile":0,"msg":"exit"}
info: {"ctx":"u:run","msg":"post-execute"}
info: {"ctx":"onDidAcceptSingle","msg":"enter","value":"Untitled-1.","opts":{"flavor":"note"},"noteOverrides":{},"selectedItems":[],"activeItems":[]}
error: {"ctx":"LookupProvider:onAccept","err":{"status":"unknown","msg":"","friendly":"something went wrong. please submit a bug report to https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title= with the output of `Dendron: Open Log`","payload":"{\"msg\":\"no workspace file\",\"stack\":\"Error: no workspace file\\n    at Function.workspaceFile (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:9:76964)\\n    at Function.wsRoot (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:9:76829)\\n    at B.get configRoot [as configRoot] (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:9:78035)\\n    at B.get config [as config] (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:9:78073)\\n    at B.get vaultsv4 [as vaultsv4] (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:9:78685)\\n    at Function.getVaultForOpenEditor (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:15:18498)\\n    at Function.getOrPromptVaultForOpenEditor (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:15:18925)\\n    at t.LookupProviderV2.onDidAcceptForSingle (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:466:1302371)\\n    at t.LookupProviderV2.onDidAccept (/Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:466:1300860)\\n    at /Users/vivek/.vscode/extensions/dendron.dendron-0.34.0/dist/extension.js:466:1304778\\n    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)\\n    at u._fireDidAccept (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:6361)\\n    at S.$onDidAccept (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:3954)\\n    at c._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:10509)\\n    at c._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:10201)\\n    at c._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8871)\\n    at c._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:7673)\\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:5782\\n    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)\\n    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15443)\\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:29119\\n    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)\\n    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15443)\\n    at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20693)\\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17587\\n    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)\\n    at l.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12808)\\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12156\\n    at Socket.E (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:12375)\\n    at Socket.emit (events.js:315:20)\\n    at addChunk (_stream_readable.js:295:12)\\n    at readableAddChunk (_stream_readable.js:271:9)\\n    at Socket.Readable.push (_stream_readable.js:212:10)\\n    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)\"}"}}

```

**Comment by kevinslin** [comment]
The right behavior would be to check if we're in a workspace and if not, disable the command. this will be added to our backlog

**Comment by kpathakota** [comment]
The Dendron extension won't load unless you're in a Dendron workspace and if the extension doesn't load, the shortcut key won't work. This is fixed.  @vivkr / @kevinslin - let me know if you still think there's a gap here.
