### ISSUE TITLE
Instructions for launching engine for `buildSiteV2`

### ISSUE THREAD

**Issue by drkstr101** [dendronhq/dendron#678]
Greetings all,

RE: https://github.com/dendronhq/dendron-site/blob/master/vault/dendron.topic.publishing.guides.md

I very much fell in love with Dendron and would like to use it for a daily journal at my company, but we don't use GitHub pages (we're on GitLab instead) and so the `buildSiteV2` sounds great. We even use Vercel already!

I am however having a bit of trouble running this command without a dendron LSP engine already started in the background (from VSCode).

When I tried this last week I didn't have any issue, but now I am getting

```
/home/amiller/watheia-mfe/knowledgespace/node_modules/.bin/dendron-cli buildSiteV2 --wsRoot . --stage prod
{"level":50,"time":1619136764957,"pid":131319,"hostname":"sfo3-watheia-01","name":"connector","name":"StatusCodeError","statusCode":404,"message":"404 - \"<!DOCTYPE HTML
...
Cannot GET /api/note/info</pre>\\n</body>\\n</html>\\n\""
```

I did in fact modify the cli command in the instructions to remove the `--` as this seemed to be squashing the remaining params.

I assume I've just done something silly this time when I go to do it for "real" this time, but I haven't been able to get past this error. Could someone pretty please get me started in the right direction?

Happy to PR if it turns out to be an actual issue and I am able to fix.

Cheers, and thank you for Dendroon!!

Workspace Root: https://gitlab.com/watheia/watheia-mfe/-/tree/master/knowledgespace

**Comment by kevinslin** [comment]
This should work without the need of an engine running (the CLI will create one). Can you make sure your using the latest version of the CLI?

**Comment by drkstr101** [comment]
```
➜  sunflower-zones git:(main) ✗ yarn dendron-cli buildSiteV2 --wsRoot .  --stage prod 
yarn run v1.22.10
$ dendron-cli buildSiteV2 --wsRoot . --stage prod
{"level":50,"time":1619779510368,"pid":63325,"hostname":"sfo3-watheia-01","name":"connector","name":"StatusCodeError","statusCode":404,"message":"404 - \"<!DOCTYPE html>\\n<html lang=\\\"en\\\">\\n<head>\\n<meta charset=\\\"utf-8\\\">\\n<title>Error</title>\\n</head>\\n<body>\\n<pre>Cannot GET /api/note/info</pre>\\n</body>\\n</html>\\n\"","error":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /api/note/info</pre>\n</body>\n</html>\n","options":{"url":"http://localhost:36437/api/note/info","qs":{},"body":{},"json":true,"method":"GET","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":404,"body":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /api/note/info</pre>\n</body>\n</html>\n","headers":{"x-powered-by":"Express","content-security-policy":"default-src 'none'","x-content-type-options":"nosniff","content-type":"text/html; charset=utf-8","content-length":"152","date":"Fri, 30 Apr 2021 10:45:10 GMT","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:36437","port":"36437","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/api/note/info","path":"/api/note/info","href":"http://localhost:36437/api/note/info"},"method":"GET","headers":{"accept":"application/json","content-type":"application/json","content-length":2}}},"stack":"StatusCodeError: 404 - \"<!DOCTYPE html>\\n<html lang=\\\"en\\\">\\n<head>\\n<meta charset=\\\"utf-8\\\">\\n<title>Error</title>\\n</head>\\n<body>\\n<pre>Cannot GET /api/note/info</pre>\\n</body>\\n</html>\\n\"\n    at new StatusCodeError (/home/amiller/sunflower/sunflower-zones/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/home/amiller/sunflower/sunflower-zones/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/home/amiller/sunflower/sunflower-zones/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/home/amiller/sunflower/sunflower-zones/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at Request.<anonymous> (/home/amiller/sunflower/sunflower-zones/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:315:20)\n    at IncomingMessage.<anonymous> (/home/amiller/sunflower/sunflower-zones/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:421:28)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","type":"Error","msg":"404 - \"<!DOCTYPE html>\\n<html lang=\\\"en\\\">\\n<head>\\n<meta charset=\\\"utf-8\\\">\\n<title>Error</title>\\n</head>\\n<body>\\n<pre>Cannot GET /api/note/info</pre>\\n</body>\\n</html>\\n\""}
dendron-cli buildSiteV2

build notes for publication using 11ty

Options:
  --version     Show version number                                    [boolean]
  --help        Show help                                              [boolean]
  --wsRoot      location of workspace                                 [required]
  --enginePort  If set, connecto to running engine. If not set, create new
                instance of Dendron Engine
  --serve       serve over local http server          [boolean] [default: false]
  --stage       serve over local http server
                                       [choices: "dev", "prod"] [default: "dev"]
  --servePort   port to serve over                             [default: "8080"]
  --output      if set, override output from config.yml                 [string]

DendronError: error connecting
    at EngineConnector.init (/home/amiller/sunflower/sunflower-zones/node_modules/@dendronhq/dendron-11ty/node_modules/@dendronhq/engine-server/lib/topics/connector.js:45:23)
    at async getEngine (/home/amiller/sunflower/sunflower-zones/node_modules/@dendronhq/dendron-11ty/libs/utils.js:40:5)
    at async getNotes (/home/amiller/sunflower/sunflower-zones/node_modules/@dendronhq/dendron-11ty/_data/notes.js:22:18)
    at async TemplateData.getDataValue (/home/amiller/sunflower/sunflower-zones/node_modules/@11ty/eleventy/src/TemplateData.js:385:23)
    at async TemplateData.getAllGlobalData (/home/amiller/sunflower/sunflower-zones/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
    at async TemplateData.getData (/home/amiller/sunflower/sunflower-zones/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)
    at async compile (/home/amiller/sunflower/sunflower-zones/node_modules/@dendronhq/dendron-11ty/index.js:32:3)
    at async BuildSiteV2CLICommand.execute (/home/amiller/sunflower/sunflower-zones/node_modules/@dendronhq/dendron-cli/lib/src/commands/build-site-v2.js:77:9) {
  status: 'unknown',
  msg: 'error connecting',
  friendly: undefined,
  payload: '{}',
  code: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I get the same error when deploying to Vercel. I probably just skipped over something obvious like "you need to publish your notes first". I will run through it again from the top.

**Comment by drkstr101** [comment]
My mistake, of course. :)

 `^0.39.2-alpha.0` works as expected.

Cheers and thank you!
