### ISSUE TITLE
Getting "Error: no template found for [object Object]" while creating a new note

### ISSUE THREAD

**Issue by leodido** [dendronhq/dendron#987]
## Please select the area your Bug applys to. (Multiple selections are Possible)

- [ ] Onboard. Initial vault setup and import/export pods 
- [x] Create. Note creation, lookup, snippets and templates
- [ ] Retrieve. Backlinks, references, graph view
- [ ] Structure. Refactoring, multi-vault and schemas
- [ ] Publish. Sharing your repo with the world
- [ ] Misc (Choose this if your not sure)

## Describe the bug

Getting `Error: no template found for [object Object]` when trying to create a new note (named "p.github.leodido.test").

## To Reproduce

Create a new note the usual way (CMD+L, type the name note).

## Expected behavior

The note to be created and the template (defined by the schema) to be applied.

## Screenshots

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/120051/125760239-d9a4ecce-2bdf-4e7b-b9df-d6e9efad84cb.png">

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/120051/125760291-7f02e0c8-cc0f-4b79-9c3f-671627718df7.png">

## Desktop (please complete the following information)

- OS: macOS 11.4
- Version: Dendron 0.50

## Additional context

The same was happening also with version 0.49.

## Dendron Log file

```
{"level":30,"time":1626339130384,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"updatePickerItems","msg":"enter","queryOrig":"p.github.leodido.test","source":"onValueChange"}
{"level":20,"time":1626339130384,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"updatePickerItems","pickerValue":"p.github.leodido.test","msg":"qs"}
{"level":30,"time":1626339130384,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"first query"}
{"level":30,"time":1626339130402,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"post:queryNotes"}
{"level":30,"time":1626339130402,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"/PATH/REDACTED/daily.journal.2021.07.15.md"}
{"level":30,"time":1626339130402,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626339130407,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"createPickerItemsFromEngine","msg":"engine.query","profile":22}
{"level":20,"time":1626339130407,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"updatePickerItems","msg":"active != qs"}
{"level":30,"time":1626339130407,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"updatePickerItems","msg":"exit","queryOrig":"p.github.leodido.test","source":"onValueChange","profile":22,"cancelled":false}
{"level":30,"time":1626339130551,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"onDidAcceptSingle","msg":"enter","value":"p.github.leodido.test","opts":{"flavor":"note"},"noteOverrides":{},"selectedItems":[{"fname":"Create New","id":"WXXhnZz0jgFtQeEU","children":[],"vault":{"fsPath":"vault"},"parent":null}],"activeItems":[{"fname":"Create New","id":"WXXhnZz0jgFtQeEU","children":[],"vault":{"fsPath":"vault"},"parent":null}]}
{"level":30,"time":1626339130552,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"onAcceptNewNode"}
{"level":30,"time":1626339130552,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"/PATH/REDACTED/daily.journal.2021.07.15.md"}
{"level":30,"time":1626339130552,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626339130552,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"onAcceptNewNode","msg":"createNewPick","value":"p.github.leodido.test"}
{"level":30,"time":1626339130552,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"getVaultForOpenEditor","activeDocument":"/PATH/REDACTED/daily.journal.2021.07.15.md"}
{"level":30,"time":1626339130552,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"getVaultForOpenEditor","msg":"exit","vault":{"fsPath":"vault"}}
{"level":30,"time":1626339130552,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"onAcceptNewNode","msg":"create normal node"}
{"level":30,"time":1626339130553,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"onAcceptNewNode","msg":"post:maybeAddSchema","schema":{"schemaModule":{"version":1,"root":{"id":"p","parent":"root","children":["blog","book","cncf","costituzionesrl","crypto","dendron","falco","github","indobox","learn","recurring","relationships","resolutions","sysdig","talk","viagargano53"]},"schemas":{"p":{"id":"p","title":"p","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"root","children":["blog","book","cncf","costituzionesrl","crypto","dendron","falco","github","indobox","learn","recurring","relationships","resolutions","sysdig","talk","viagargano53"],"body":"","data":{}},"blog":{"id":"blog","title":"blog","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":["blog-year"],"body":"","data":{}},"blog-year":{"id":"blog-year","title":"blog-year","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"blog","children":["blog-id"],"body":"","data":{"pattern":"[0-9][0-9][0-9][0-9]"}},"blog-id":{"id":"blog-id","title":"blog-id","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"blog-year","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.blog","type":"note"}}},"book":{"id":"book","title":"book","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":["book-project"],"body":"","data":{}},"book-project":{"id":"book-project","title":"book-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"book","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"cncf":{"id":"cncf","title":"cncf","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":["cncf-kubecon","cncf-security-tag"],"body":"","data":{}},"cncf-kubecon":{"id":"cncf-kubecon","title":"cncf-kubecon","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"cncf","children":["cncf-kubecon-year"],"body":"","data":{"pattern":"kubecon"}},"cncf-kubecon-year":{"id":"cncf-kubecon-year","title":"cncf-kubecon-year","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"cncf-kubecon","children":["cncf-kubecon-zone"],"body":"","data":{"pattern":"[0-9][0-9][0-9][0-9]"}},"cncf-kubecon-zone":{"id":"cncf-kubecon-zone","title":"cncf-kubecon-zone","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"cncf-kubecon-year","children":["cncf-kubecon-project"],"body":"","data":{"pattern":"*"}},"cncf-kubecon-project":{"id":"cncf-kubecon-project","title":"cncf-kubecon-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"cncf-kubecon-zone","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"cncf-security-tag":{"id":"cncf-security-tag","title":"cncf-security-tag","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"cncf","children":["cncf-security-tag-project"],"body":"","data":{"pattern":"security-tag"}},"cncf-security-tag-project":{"id":"cncf-security-tag-project","title":"cncf-security-tag-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"cncf-security-tag","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"costituzionesrl":{"id":"costituzionesrl","title":"costituzionesrl","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":[],"body":"","data":{"namespace":true,"template":{"id":"template.project","type":"note"}}},"crypto":{"id":"crypto","title":"crypto","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":["crypto-year"],"body":"","data":{}},"crypto-year":{"id":"crypto-year","title":"crypto-year","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"crypto","children":["crypto-id"],"body":"","data":{"pattern":"[0-9][0-9][0-9][0-9]"}},"crypto-id":{"id":"crypto-id","title":"crypto-id","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"crypto-year","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"dendron":{"id":"dendron","title":"dendron","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":["dendron-project"],"body":"","data":{}},"dendron-project":{"id":"dendron-project","title":"dendron-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"dendron","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"falco":{"id":"falco","title":"falco","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":["falco-project"],"body":"","data":{}},"falco-project":{"id":"falco-project","title":"falco-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"falco","children":["falco-subproject"],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"falco-subproject":{"id":"falco-subproject","title":"falco-subproject","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"falco-project","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"github":{"id":"github","title":"github","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":["github-org"],"body":"","data":{}},"github-org":{"id":"github-org","title":"github-org","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"github","children":["github-repo"],"body":"","data":{"pattern":"*"}},"github-repo":{"id":"github-repo","title":"github-repo","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"github-org","children":["github-task"],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"github-task":{"id":"github-task","title":"github-task","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"github-repo","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"indobox":{"id":"indobox","title":"indobox","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"p","children":["indobox-project"],"body":"","data":{}},"indobox-project":{"id":"indobox-project","title":"indobox-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"indobox","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"learn":{"id":"learn","title":"learn","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962966,"parent":"p","children":["learn-subject"],"body":"","data":{}},"learn-subject":{"id":"learn-subject","title":"learn-subject","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"learn","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project.learn","type":"note"}}},"recurring":{"id":"recurring","title":"recurring","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"p","children":["recurring-project"],"body":"","data":{}},"recurring-project":{"id":"recurring-project","title":"recurring-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"recurring","children":["recurring-subproject"],"body":"","data":{"pattern":"*","template":{"id":"template.project.recurring","type":"note"}}},"recurring-subproject":{"id":"recurring-subproject","title":"recurring-subproject","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"recurring-project","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project.recurring","type":"note"}}},"relationships":{"id":"relationships","title":"relationships","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"p","children":["relationships-project"],"body":"","data":{}},"relationships-project":{"id":"relationships-project","title":"relationships-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"relationships","children":[],"body":"","data":{"pattern":"*"}},"resolutions":{"id":"resolutions","title":"resolutions","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"p","children":["resolutions-year"],"body":"","data":{}},"resolutions-year":{"id":"resolutions-year","title":"resolutions-year","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"resolutions","children":[],"body":"","data":{"pattern":"[0-9][0-9][0-9][0-9]","template":{"id":"template.resolutions","type":"note"}}},"sysdig":{"id":"sysdig","title":"sysdig","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"p","children":["sysdig-project"],"body":"","data":{}},"sysdig-project":{"id":"sysdig-project","title":"sysdig-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"sysdig","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"talk":{"id":"talk","title":"talk","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"p","children":["talk-year"],"body":"","data":{}},"talk-year":{"id":"talk-year","title":"talk-year","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"talk","children":["talk-month"],"body":"","data":{"pattern":"[0-9][0-9][0-9][0-9]"}},"talk-month":{"id":"talk-month","title":"talk-month","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"talk-year","children":["talk-day"],"body":"","data":{"pattern":"[0-9][0-9]"}},"talk-day":{"id":"talk-day","title":"talk-day","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"talk-month","children":["talk-project"],"body":"","data":{"pattern":"[0-3][0-9]"}},"talk-project":{"id":"talk-project","title":"talk-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"talk-day","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project.talk","type":"note"}}},"viagargano53":{"id":"viagargano53","title":"viagargano53","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"p","children":["viagargano53-project"],"body":"","data":{}},"viagargano53-project":{"id":"viagargano53-project","title":"viagargano53-project","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962966,"created":1626338962966,"parent":"viagargano53","children":[],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}}},"fname":"p","vault":{"fsPath":"vault"}},"schema":{"id":"github-repo","title":"github-repo","vault":{"fsPath":"vault"},"type":"schema","desc":"","links":[],"anchors":{},"fname":"__empty","updated":1626338962965,"created":1626338962965,"parent":"github-org","children":["github-task"],"body":"","data":{"pattern":"*","template":{"id":"template.project","type":"note"}}},"namespace":false,"notePath":"p.github.leodido.test"}}
{"level":50,"time":1626339130553,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"onDidAcceptSingle","error":{"stack":"Error: no template found for [object Object]\n    at Function.applyTemplate (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:238:94843)\n    at t.LookupProviderV2._onAcceptNewNote (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:572802)\n    at t.LookupProviderV2.onAcceptNewNode (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:574397)\n    at t.LookupProviderV2.onDidAcceptForSingle (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:575669)\n    at t.LookupProviderV2.onDidAccept (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:574698)\n    at /HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:578891\n    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\n    at t._fireDidAccept (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:6375)\n    at w.$onDidAccept (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:3968)\n    at u._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12743)\n    at u._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12435)\n    at u._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11097)\n    at u._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9900)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8004\n    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\n    at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29793\n    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\n    at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)\n    at r._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21035)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17921\n    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\n    at c.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13138)\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12486\n    at Socket._ (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13107)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)","message":"no template found for [object Object]"}}
{"level":50,"time":1626339130554,"pid":49583,"hostname":"REDACTED","name":"dendron","ctx":"LookupProvider:onAccept","error":{"stack":"Error: something went wrong. please submit a bug report to https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title= with the output of `Dendron: Open Log`\n    at /HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:578989\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","message":"something went wrong. please submit a bug report to https://github.com/dendronhq/dendron/issues/new?assignees=&labels=&template=bug_report.md&title= with the output of `Dendron: Open Log`","isComposite":false,"status":"unknown","payload":"{\"msg\":\"no template found for [object Object]\",\"stack\":\"Error: no template found for [object Object]\\n    at Function.applyTemplate (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:238:94843)\\n    at t.LookupProviderV2._onAcceptNewNote (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:572802)\\n    at t.LookupProviderV2.onAcceptNewNode (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:574397)\\n    at t.LookupProviderV2.onDidAcceptForSingle (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:575669)\\n    at t.LookupProviderV2.onDidAccept (/HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:574698)\\n    at /HOME/REDACTED/.vscode-insiders/extensions/dendron.dendron-0.50.0/dist/extension.js:297:578891\\n    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\\n    at t._fireDidAccept (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:6375)\\n    at w.$onDidAccept (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:3968)\\n    at u._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12743)\\n    at u._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12435)\\n    at u._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11097)\\n    at u._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9900)\\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8004\\n    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\\n    at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)\\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29793\\n    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\\n    at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)\\n    at r._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21035)\\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17921\\n    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)\\n    at c.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13138)\\n    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12486\\n    at Socket._ (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13107)\\n    at Socket.emit (events.js:315:20)\\n    at addChunk (internal/streams/readable.js:309:12)\\n    at readableAddChunk (internal/streams/readable.js:284:9)\\n    at Socket.Readable.push (internal/streams/readable.js:223:10)\\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)\"}"}}
```

**Comment by kevinslin** [comment]
thanks for the report. @leodido can you confirm if the `template.project` note still exists?

**Comment by leodido** [comment]
I confirm. The `template.project` existed.

To workaround the problem I created another template (called `template.p`) and that worked without changing anything else in the schema.
